module.exports = {
  categories: [
    // ====================================================================================================================
    // === ۱. حیوانات (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'حیوانات',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'گربه', level: 'easy', description: 'حیوان خانگی کوچک و چابک.' },
        { text: 'سگ', level: 'easy', description: 'دوست وفادار انسان و نگهبان.' },
        { text: 'اسب', level: 'easy', description: 'حیوان سواری سم‌دار و سریع.' },
        { text: 'شیر', level: 'easy', description: 'ملقب به سلطان جنگل با یال باشکوه.' },
        { text: 'ببر', level: 'easy', description: 'بزرگترین گربه‌سان جهان، راه‌راه.' },
        { text: 'کلاغ', level: 'easy', description: 'پرنده سیاه و باهوش با صدای خشن.' },
        { text: 'روباه', level: 'easy', description: 'حیوان همه‌چیزخوار معروف به حیله‌گری.' },
        { text: 'فیل', level: 'easy', description: 'بزرگترین حیوان خشکی با خرطوم.' },
        { text: 'طوطی', level: 'easy', description: 'پرنده رنگارنگ با قابلیت تقلید صدا.' },
        { text: 'قو', level: 'easy', description: 'پرنده آبزی زیبا با گردنی بلند.' },
        { text: 'مار', level: 'easy', description: 'خزنده بدون دست و پا، سمی یا غیر سمی.' },
        { text: 'ماهی', level: 'easy', description: 'حیوان آبزی با باله و آبشش.' },
        { text: 'گاو', level: 'easy', description: 'پستاندار اهلی برای تولید شیر و گوشت.' },
        { text: 'موش', level: 'easy', description: 'جونده کوچک و معمولاً آفت.' },
        { text: 'زنبور', level: 'easy', description: 'حشره بالدار که عسل تولید می‌کند.' },
        { text: 'عقاب', level: 'easy', description: 'پرنده شکاری قدرتمند و تیزبین.' },
        { text: 'گنجشک', level: 'easy', description: 'پرنده کوچک و پر سر و صدا.' },
        { text: 'اردک', level: 'easy', description: 'پرنده آبزی اهلی با صدای کواک.' },
        { text: 'شتر', level: 'easy', description: 'حیوان بیابانی با یک یا دو کوهان.' },
        { text: 'پلیکان', level: 'easy', description: 'پرنده آبزی با کیسه زیر نوک.' },
        { text: 'بز', level: 'easy', description: 'پستاندار اهلی که از شیر آن پنیر درست می‌شود.' },
        { text: 'قناری', level: 'easy', description: 'پرنده کوچک با صدای خوش.' },
        { text: 'گوزن', level: 'easy', description: 'پستاندار گیاه‌خوار با شاخ.' },
        { text: 'کبک', level: 'easy', description: 'پرنده کوهی با بال‌های کوتاه.' },
        { text: 'عنکبوت', level: 'easy', description: 'حشره هشت‌پا که تار می‌تند.' },
        { text: 'غزال', level: 'easy', description: 'نوعی آهو، نماد زیبایی.' },
        { text: 'سیمرغ', level: 'easy', description: 'پرنده افسانه‌ای در اساطیر ایران.' },
        { text: 'دلفین', level: 'easy', description: 'پستاندار دریایی باهوش و بازیگوش.' },
        { text: 'قوچ', level: 'easy', description: 'گوسفند نر شاخ‌دار.' },
        { text: 'آهو', level: 'easy', description: 'حیوان سریع و زیبا با چشمان درشت.' },
        { text: 'کرکس', level: 'easy', description: 'پرنده بزرگ مردارخوار.' },
        { text: 'فلامینگو', level: 'easy', description: 'پرنده بلندپا و صورتی.' },
        { text: 'آفتاب پرست', level: 'easy', description: 'خزنده کوچک که رنگ عوض می‌کند.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'خرگوش', level: 'medium', description: 'پستاندار کوچک با گوش‌های بلند.' },
        { text: 'زرافه', level: 'medium', description: 'بلندترین حیوان جهان با گردن دراز.' },
        { text: 'پنگوئن', level: 'medium', description: 'پرنده دریایی که پرواز نمی‌کند.' },
        { text: 'تمساح', level: 'medium', description: 'خزنده آبزی بزرگ با آرواره‌های قوی.' },
        { text: 'پلنگ', level: 'medium', description: 'گربه‌سان خال‌دار با قابلیت بالا رفتن از درخت.' },
        { text: 'سنجاب', level: 'medium', description: 'جونده کوچک که بلوط ذخیره می‌کند.' },
        { text: 'مارمولک', level: 'medium', description: 'خزنده کوچک با چهار دست و پا.' },
        { text: 'میمون', level: 'medium', description: 'نخستی باهوش که از درخت بالا می‌رود.' },
        { text: 'گرگ', level: 'medium', description: 'شکارچی شب‌گرد که در گله زندگی می‌کند.' },
        { text: 'کفتار', level: 'medium', description: 'شکارچی و مردارخوار با صدای خنده عجیب.' },
        { text: 'سوسمار', level: 'medium', description: 'خزنده بزرگ با دم بلند.' },
        { text: 'نهنگ', level: 'medium', description: 'پستاندار بزرگ دریایی.' },
        { text: 'کرگدن', level: 'medium', description: 'پستاندار بزرگ آفریقایی با شاخ روی بینی.' },
        { text: 'سار', level: 'medium', description: 'پرنده کوچک و پر سر و صدا.' },
        { text: 'کوسه', level: 'medium', description: 'ماهی شکارچی بزرگ با دندان‌های تیز.' },
        { text: 'دارکوب', level: 'medium', description: 'پرنده‌ای که با نوکش به درخت ضربه می‌زند.' },
        { text: 'بوفالو', level: 'medium', description: 'گاو وحشی بزرگ و قوی.' },
        { text: 'شاهین', level: 'medium', description: 'پرنده شکاری سریع و آموزش‌پذیر.' },
        { text: 'غواص', level: 'medium', description: 'نوعی مرغابی که در آب شیرجه می‌زند.' },
        { text: 'گورخر', level: 'medium', description: 'حیوان آفریقایی شبیه اسب با نوارهای سیاه و سفید.' },
        { text: 'راسو', level: 'medium', description: 'پستاندار گوشت‌خوار با بوی بد.' },
        { text: 'سگ ماهی', level: 'medium', description: 'نوعی ماهی کوچک و تندرو.' },
        { text: 'حلزون', level: 'medium', description: 'نرم‌تنی که یک خانه صدفی با خود حمل می‌کند.' },
        { text: 'سوسک', level: 'medium', description: 'حشره سیاه رنگ و مقاوم.' },
        { text: 'آخوندک', level: 'medium', description: 'حشره‌ای با دست‌های تاشو شبیه به حالت دعا.' },
        { text: 'عقرب', level: 'medium', description: 'حشره با نیش سمی در انتهای دم.' },
        { text: 'سمور', level: 'medium', description: 'پستاندار خزدار با ارزش.' },
        { text: 'بوقلمون', level: 'medium', description: 'پرنده بزرگ و اهلی که برای گوشت پرورش می‌یابد.' },
        { text: 'گوریل', level: 'medium', description: 'بزرگترین نوع میمون در جهان.' },
        { text: 'سنجاب پرنده', level: 'medium', description: 'نوعی سنجاب با قابلیت گلاید.' },
        { text: 'آرمادیلو', level: 'medium', description: 'حیوان کوچک آمریکایی با پوست سخت و زره مانند.' },
        { text: 'جوجه تیغی', level: 'medium', description: 'پستاندار کوچک با خارهای محافظ.' },
        { text: 'ایگوانا', level: 'medium', description: 'نوعی سوسمار بزرگ گیاه‌خوار.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'خرس قهوه ای', level: 'hard', description: 'حیوان بزرگ و قوی که در جنگل‌ها زندگی می‌کند.' },
        { text: 'بز کوهی', level: 'hard', description: 'حیوان کوهستان با شاخ‌های بلند و خمیده.' },
        { text: 'نهنگ آبی', level: 'hard', description: 'بزرگترین حیوان کره زمین.' },
        { text: 'یوزپلنگ', level: 'hard', description: 'سریع‌ترین حیوان خشکی.' },
        { text: 'مار پیتون', level: 'hard', description: 'مار بزرگ و غیر سمی که طعمه را خفه می‌کند.' },
        { text: 'مرغ ماهیخوار', level: 'hard', description: 'پرنده‌ای با بال‌های دراز که از آب ماهی می‌گیرد.' },
        { text: 'کانگورو', level: 'hard', description: 'پستاندار کیسه‌دار استرالیایی که با جهش حرکت می‌کند.' },
        { text: 'هشت پا', level: 'hard', description: 'جانور دریایی با هشت بازو.' },
        { text: 'شیر دریایی', level: 'hard', description: 'پستاندار دریایی با باله‌های پارو مانند.' },
        { text: 'جوجه تیغی', level: 'hard', description: 'حیوان کوچک با خارهای تند روی پشت.' },
        { text: 'خوکچه هندی', level: 'hard', description: 'جونده کوچک و اهلی.' },
        { text: 'راسو', level: 'hard', description: 'حیوان کوچک که بوی بدی منتشر می‌کند.' },
        { text: 'پرنده بهشتی', level: 'hard', description: 'پرنده‌ای با پرهای بسیار زیبا.' },
        { text: 'اسب آبی', level: 'hard', description: 'پستاندار بزرگ نیمه‌آبزی آفریقایی.' },
        { text: 'مار کبری', level: 'hard', description: 'مار سمی که گردن خود را پهن می‌کند.' },
        { text: 'اردک ماهی', level: 'hard', description: 'نوعی ماهی شکارچی آب شیرین.' },
        { text: 'گربه سان', level: 'hard', description: 'حیواناتی از خانواده گربه، مانند شیر و ببر.' },
        { text: 'عنکبوت رتیل', level: 'hard', description: 'بزرگترین و مودارترین نوع عنکبوت.' },
        { text: 'سوسمار درختی', level: 'hard', description: 'مارمولکی که در درختان زندگی می‌کند.' },
        { text: 'گاو کوهان دار', level: 'hard', description: 'نوعی گاو با کوهان روی پشت.' },
        { text: 'فیل دریایی', level: 'hard', description: 'پستاندار دریایی بزرگ با خرطوم کوتاه.' },
        { text: 'عقاب ماهیگیر', level: 'hard', description: 'نوعی عقاب که تخصصش شکار ماهی است.' },
        { text: 'بزغاله', level: 'hard', description: 'نوزاد بز.' },
        { text: 'گوسفند دریایی', level: 'hard', description: 'نوعی پستاندار دریایی گیاه‌خوار.' },
        { text: 'شاه‌میگو', level: 'hard', description: 'نوعی سخت‌پوست خوراکی بزرگ.' },
        { text: 'جغد سفید', level: 'hard', description: 'جغدی که کاملاً سفید است.' },
        { text: 'آفریقایی', level: 'hard', description: 'در توصیف حیواناتی که در آفریقا زندگی می‌کنند.' },
        { text: 'پروانه مونارک', level: 'hard', description: 'نوعی پروانه با مهاجرت‌های طولانی.' },
        { text: 'گواناکو', level: 'hard', description: 'نوعی شتر بدون کوهان از آمریکای جنوبی.' },
        { text: 'گرگ تاسمانی', level: 'hard', description: 'پستاندار منقرض شده شبیه گرگ با نوارهای پشت.' },
        { text: 'خرس کوالا', level: 'hard', description: 'حیوان کیسه‌دار استرالیایی که از برگ اکالیپتوس تغذیه می‌کند.' },
        { text: 'کرم ابریشم', level: 'hard', description: 'لارو پروانه که ابریشم تولید می‌کند.' },
        { text: 'سفره ماهی', level: 'hard', description: 'ماهی پهن و بزرگ دریایی.' },
        { text: 'دوزیست', level: 'hard', description: 'حیواناتی که در آب و خشکی زندگی می‌کنند (مانند قورباغه).' },
      ],
    },

    // ====================================================================================================================
    // === ۲. میوه‌ها (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'میوه ها',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'سیب', level: 'easy', description: 'میوه‌ای گرد و معمولاً قرمز یا سبز.' },
        { text: 'موز', level: 'easy', description: 'میوه استوایی و دراز با پوست زرد.' },
        { text: 'انار', level: 'easy', description: 'میوه‌ای با دانه‌های آبدار و سرخ.' },
        { text: 'کیوی', level: 'easy', description: 'میوه‌ای با پوست قهوه‌ای کرک‌دار.' },
        { text: 'هلو', level: 'easy', description: 'میوه‌ای آبدار با پوست کرکی.' },
        { text: 'آلو', level: 'easy', description: 'میوه‌ای با پوست صاف و رنگ بنفش یا قرمز.' },
        { text: 'گیلاس', level: 'easy', description: 'میوه کوچک و قرمز براق.' },
        { text: 'انگور', level: 'easy', description: 'میوه‌ای کوچک که به صورت خوشه رشد می‌کند.' },
        { text: 'آلبالو', level: 'easy', description: 'میوه‌ای ترش و شبیه گیلاس.' },
        { text: 'به', level: 'easy', description: 'میوه سفت و زرد که پخته مصرف می‌شود.' },
        { text: 'زرد آلو', level: 'easy', description: 'میوه کوچکی شبیه هلو با رنگ نارنجی.' },
        { text: 'توت', level: 'easy', description: 'میوه کوچک و شیرین که روی درخت می‌روید.' },
        { text: 'خرما', level: 'easy', description: 'میوه گرمسیری با طعم شیرین.' },
        { text: 'فندق', level: 'easy', description: 'مغز خوراکی با پوسته سخت.' },
        { text: 'پسته', level: 'easy', description: 'مغز سبز رنگ و گران‌بها.' },
        { text: 'گردو', level: 'easy', description: 'مغز خوراکی که شبیه مغز انسان است.' },
        { text: 'زیتون', level: 'easy', description: 'میوه کوچک با طعم تلخ که روغن آن گرفته می‌شود.' },
        { text: 'لیمو', level: 'easy', description: 'مرکباتی کوچک و ترش.' },
        { text: 'بلوبری', level: 'easy', description: 'میوه ریز و آبی تیره.' },
        { text: 'تمشک', level: 'easy', description: 'میوه جنگلی کوچک و ترش.' },
        { text: 'ازگیل', level: 'easy', description: 'میوه کوچک و گس پاییزی.' },
        { text: 'کنجد', level: 'easy', description: 'دانه روغنی کوچک.' },
        { text: 'سنجد', level: 'easy', description: 'میوه کوچک و پودری شکل در سفره هفت سین.' },
        { text: 'نارنج', level: 'easy', description: 'مرکباتی بسیار ترش.' },
        { text: 'کدو', level: 'easy', description: 'میوه بزرگ با پوست سخت که در غذا و تزیین استفاده می‌شود.' },
        { text: 'بادام', level: 'easy', description: 'مغز خوراکی شیرین یا تلخ.' },
        { text: 'پاپایا', level: 'easy', description: 'میوه استوایی با گوشت نارنجی.' },
        { text: 'فلفل', level: 'easy', description: 'میوه‌ای که به عنوان ادویه یا سبزی مصرف می‌شود.' },
        { text: 'ریواس', level: 'easy', description: 'ساقه‌ای ترش که در تهیه خورشت و شربت استفاده می‌شود.' },
        { text: 'زیره', level: 'easy', description: 'دانه معطر که به عنوان ادویه استفاده می‌شود.' },
        { text: 'چای', level: 'easy', description: 'برگ درختچه‌ای که برای تهیه نوشیدنی گرم استفاده می‌شود.' },
        { text: 'کاهو', level: 'easy', description: 'سبزی با برگ‌های پهن برای سالاد.' },
        { text: 'کلم', level: 'easy', description: 'سبزی با برگ‌های متراکم.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'پرتقال', level: 'medium', description: 'مرکباتی با پوست نارنجی و ویتامین C بالا.' },
        { text: 'گلابی', level: 'medium', description: 'میوه‌ای شیرین و آبدار شبیه لامپ.' },
        { text: 'طالبی', level: 'medium', description: 'میوه‌ای گرد و خوشبو با گوشت نارنجی.' },
        { text: 'ملون', level: 'medium', description: 'میوه‌ای شیرین و معطر، شبیه طالبی.' },
        { text: 'انبه', level: 'medium', description: 'میوه شیرین و خوشبوی مناطق گرمسیری.' },
        { text: 'نارگیل', level: 'medium', description: 'میوه‌ای سخت با مغز سفید و شیر نارگیل.' },
        { text: 'گریپ فروت', level: 'medium', description: 'مرکبات بزرگ با طعم تلخ و ترش.' },
        { text: 'خرمالو', level: 'medium', description: 'میوه پاییزی که تا کاملاً نرسد، گس است.' },
        { text: 'شلیل', level: 'medium', description: 'نوعی هلو بدون پوست کرکی.' },
        { text: 'انجیر', level: 'medium', description: 'میوه شیرین و نرم که تازه یا خشک مصرف می‌شود.' },
        { text: 'آناناس', level: 'medium', description: 'میوه استوایی با پوست سخت و تاج برگدار.' },
        { text: 'بادمجان', level: 'medium', description: 'سبزی بنفش یا سیاه رنگ برای پخت و پز.' },
        { text: 'کرفس', level: 'medium', description: 'ساقه‌ای ترد برای سالاد و خورشت.' },
        { text: 'کدو حلوایی', level: 'medium', description: 'کدوی شیرین که برای دسر یا خوراک استفاده می‌شود.' },
        { text: 'دارچین', level: 'medium', description: 'پوست معطر درختی که به عنوان ادویه استفاده می‌شود.' },
        { text: 'سماق', level: 'medium', description: 'ادویه ترش قرمز رنگ که روی کباب پاشیده می‌شود.' },
        { text: 'زنجبیل', level: 'medium', description: 'ریشه گیاهی که به عنوان ادویه استفاده می‌شود.' },
        { text: 'هل', level: 'medium', description: 'دانه‌ای معطر برای چای و شیرینی.' },
        { text: 'زرشک', level: 'medium', description: 'میوه کوچک و ترش که در پلو استفاده می‌شود.' },
        { text: 'گوجه فرنگی', level: 'medium', description: 'میوه‌ای قرمز رنگ که به عنوان سبزی در غذا استفاده می‌شود.' },
        { text: 'آووکادو', level: 'medium', description: 'میوه‌ای با گوشت سبز و چرب.' },
        { text: 'زغال اخته', level: 'medium', description: 'میوه کوچک و تیره رنگ با طعم ترش.' },
        { text: 'شاه توت', level: 'medium', description: 'میوه سیاه رنگ و آبدار شبیه توت.' },
        { text: 'زنجبیل', level: 'medium', description: 'ریشه گیاهی معطر و تند.' },
        { text: 'خیار', level: 'medium', description: 'میوه‌ای سبز و خنک که در سالاد استفاده می‌شود.' },
        { text: 'پیاز', level: 'medium', description: 'سبزی با بوی تند که در آشپزی کاربرد فراوان دارد.' },
        { text: 'سیر', level: 'medium', description: 'ساقه زیرزمینی با بوی قوی که در آشپزی استفاده می‌شود.' },
        { text: 'سیب زمینی', level: 'medium', description: 'ریشه نشاسته‌ای که غذای اصلی بسیاری از مردم است.' },
        { text: 'هویج', level: 'medium', description: 'ریشه نارنجی رنگ و شیرین.' },
        { text: 'کلم بروکلی', level: 'medium', description: 'سبزی سبز رنگ شبیه درخت کوچک.' },
        { text: 'مارچوبه', level: 'medium', description: 'سبزی با ساقه نازک که طعم دلپذیری دارد.' },
        { text: 'لوبیا سبز', level: 'medium', description: 'غلاف سبز رنگ که حاوی دانه‌های خوراکی است.' },
        { text: 'ذرت', level: 'medium', description: 'دانه‌ای که روی بلال می‌روید.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'هندوانه', level: 'hard', description: 'میوه بزرگ تابستانی با پوست سبز و داخل قرمز.' },
        { text: 'توت فرنگی', level: 'hard', description: 'میوه کوچک، قرمز و خوشبو با دانه‌های ریز.' },
        { text: 'لیمو شیرین', level: 'hard', description: 'مرکباتی بزرگ شبیه لیمو ترش با طعمی شیرین.' },
        { text: 'لیمو ترش', level: 'hard', description: 'مرکباتی کوچک، سبز یا زرد با طعمی بسیار ترش.' },
        { text: 'میوۀ اژدها', level: 'hard', description: 'میوه استوایی با پوست صورتی و فلس‌دار.' },
        { text: 'گلابی جنگلی', level: 'hard', description: 'نوعی گلابی با اندازه کوچک‌تر و طعم وحشی.' },
        { text: 'دارابی', level: 'hard', description: 'نوعی مرکبات بزرگ و سنگین شبیه گریپ فروت.' },
        { text: 'ازگیل ژاپنی', level: 'hard', description: 'میوه کوچک و نارنجی رنگ با طعم ترش و شیرین.' },
        { text: 'شاه بلوط', level: 'hard', description: 'مغز خوراکی بزرگ که معمولاً به صورت پخته مصرف می‌شود.' },
        { text: 'لوبیا چیتی', level: 'hard', description: 'نوعی لوبیا با طرح‌های رنگی روی دانه.' },
        { text: 'نخود فرنگی', level: 'hard', description: 'دانه سبز و کوچک که در غلاف رشد می‌کند.' },
        { text: 'نخود سیاه', level: 'hard', description: 'نوعی نخود که رنگ تیره دارد.' },
        { text: 'باقالی', level: 'hard', description: 'دانه سبز و بزرگ که در پلو و آش استفاده می‌شود.' },
        { text: 'کلم قمری', level: 'hard', description: 'نوعی کلم با ساقه پف کرده و گرد.' },
        { text: 'جعفری', level: 'hard', description: 'سبزی معطر برای تزیین غذا.' },
        { text: 'ریحان', level: 'hard', description: 'سبزی خوشبو با برگ‌های بنفش یا سبز.' },
        { text: 'شاهی', level: 'hard', description: 'سبزی تند و پر ویتامین.' },
        { text: 'تره', level: 'hard', description: 'سبزی با برگ‌های بلند و شبیه پیازچه.' },
        { text: 'شوید', level: 'hard', description: 'سبزی معطر که در پلو و ماهی استفاده می‌شود.' },
        { text: 'گشنیز', level: 'hard', description: 'سبزی معطر که در آش و سوپ استفاده می‌شود.' },
        { text: 'اسفناج', level: 'hard', description: 'سبزی با برگ‌های بزرگ که سرشار از آهن است.' },
        { text: 'پیازچه', level: 'hard', description: 'نوعی پیاز با برگ‌های بلند و سبز.' },
        { text: 'لیمو عمانی', level: 'hard', description: 'لیموی خشک شده که در خورشت‌ها استفاده می‌شود.' },
        { text: 'فیسالیس', level: 'hard', description: 'میوه کوچک و نارنجی با پوست کاغذی.' },
        { text: 'گوار', level: 'hard', description: 'نوعی لوبیا که در مناطق خشک می‌روید.' },
        { text: 'پاپیتال', level: 'hard', description: 'نوعی گیاه با میوه‌های سمی و برگ‌های همیشه سبز.' },
        { text: 'بامبو', level: 'hard', description: 'ساقه گیاهی که در آسیا به عنوان سبزیجات خورده می‌شود.' },
        { text: 'زنجبیل چینی', level: 'hard', description: 'نوعی زنجبیل که در آشپزی چینی استفاده می‌شود.' },
        { text: 'برگ بو', level: 'hard', description: 'برگ معطر که در غذاها برای طعم‌دهی استفاده می‌شود.' },
        { text: 'کنجد سیاه', level: 'hard', description: 'نوعی کنجد که رنگ سیاه دارد.' },
        { text: 'عدس', level: 'hard', description: 'حبوبات کوچک و گرد که برای پخت پلو و آش استفاده می‌شود.' },
        { text: 'ماش', level: 'hard', description: 'حبوبات کوچک و سبز رنگ.' },
        { text: 'لوبیا قرمز', level: 'hard', description: 'نوعی لوبیا با رنگ قرمز.' },
        { text: 'نخود', level: 'hard', description: 'حبوبات بزرگ و زرد رنگ.' },
      ],
    },

    // ====================================================================================================================
    // === ۳. شهرها و مکان‌ها (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'شهرها و مکان ها',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'تهران', level: 'easy', description: 'پایتخت ایران و بزرگترین شهر کشور.' },
        { text: 'قم', level: 'easy', description: 'شهر مذهبی و میزبان حرم حضرت معصومه.' },
        { text: 'رشت', level: 'easy', description: 'مرکز استان گیلان، پرباران و همیشه سبز.' },
        { text: 'ساری', level: 'easy', description: 'مرکز استان مازندران و نزدیک به دریا.' },
        { text: 'یزد', level: 'easy', description: 'شهر بادگیرها و اولین شهر خشتی جهان.' },
        { text: 'تبریز', level: 'easy', description: 'مرکز استان آذربایجان شرقی.' },
        { text: 'مشهد', level: 'easy', description: 'میزبان حرم امام رضا و دومین شهر بزرگ ایران.' },
        { text: 'کرج', level: 'easy', description: 'مرکز استان البرز و شهری پرجمعیت.' },
        { text: 'بم', level: 'easy', description: 'شهری در کرمان با ارگ تاریخی بزرگ.' },
        { text: 'سمنان', level: 'easy', description: 'شهری در مسیر کویر با آب و هوای خشک.' },
        { text: 'آمل', level: 'easy', description: 'شهری در مازندران با تاریخچه کهن.' },
        { text: 'بابل', level: 'easy', description: 'شهری مهم در مازندران.' },
        { text: 'اهواز', level: 'easy', description: 'مرکز استان خوزستان و شهری گرم.' },
        { text: 'کاشان', level: 'easy', description: 'شهر تاریخی و مرکز تولید گلاب.' },
        { text: 'ورامین', level: 'easy', description: 'شهری در نزدیکی تهران.' },
        { text: 'ری', level: 'easy', description: 'شهری باستانی در جنوب تهران.' },
        { text: 'بانه', level: 'easy', description: 'شهری مرزی در کردستان، معروف به تجارت.' },
        { text: 'شوش', level: 'easy', description: 'شهری باستانی در خوزستان.' },
        { text: 'آبادان', level: 'easy', description: 'بندر و شهر نفتی در خوزستان.' },
        { text: 'کیش', level: 'easy', description: 'جزیره‌ای توریستی در خلیج فارس.' },
        { text: 'قشم', level: 'easy', description: 'بزرگترین جزیره ایران در خلیج فارس.' },
        { text: 'چالوس', level: 'easy', description: 'شهر ساحلی در مازندران.' },
        { text: 'آرادان', level: 'easy', description: 'شهری در استان سمنان.' },
        { text: 'لنگرود', level: 'easy', description: 'شهری در استان گیلان.' },
        { text: 'تفت', level: 'easy', description: 'شهری در نزدیکی یزد.' },
        { text: 'لار', level: 'easy', description: 'شهری در استان فارس.' },
        { text: 'تکاب', level: 'easy', description: 'شهری در استان آذربایجان غربی.' },
        { text: 'نمین', level: 'easy', description: 'شهری در استان اردبیل.' },
        { text: 'مرو', level: 'easy', description: 'شهر تاریخی در ترکمنستان امروزی.' },
        { text: 'خوی', level: 'easy', description: 'شهری در استان آذربایجان غربی.' },
        { text: 'جیرفت', level: 'easy', description: 'شهری با تمدن باستانی در کرمان.' },
        { text: 'دهدشت', level: 'easy', description: 'شهری در استان کهگیلویه و بویراحمد.' },
        { text: 'جاده چالوس', level: 'easy', description: 'جاده‌ای کوهستانی و زیبا.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'اصفهان', level: 'medium', description: 'شهر گنبدهای فیروزه‌ای و نصف جهان.' },
        { text: 'شیراز', level: 'medium', description: 'شهر شعر و ادب، حافظیه و سعدیه.' },
        { text: 'کرمان', level: 'medium', description: 'مرکز تولید پسته و زیره در ایران.' },
        { text: 'اردبیل', level: 'medium', description: 'شهر چشمه‌های آب گرم و آرامگاه شیخ صفی.' },
        { text: 'زنجان', level: 'medium', description: 'مرکز چاقو و ملیله‌کاری در ایران.' },
        { text: 'گرگان', level: 'medium', description: 'مرکز استان گلستان با آب و هوای معتدل.' },
        { text: 'بوشهر', level: 'medium', description: 'بندر جنوبی و گرم با معماری سنتی.' },
        { text: 'همدان', level: 'medium', description: 'یکی از قدیمی‌ترین شهرهای ایران.' },
        { text: 'اراک', level: 'medium', description: 'مرکز استان مرکزی و قطب صنعتی.' },
        { text: 'ارومیه', level: 'medium', description: 'مرکز استان آذربایجان غربی.' },
        { text: 'بیرجند', level: 'medium', description: 'شهر زعفران و عناب در خراسان جنوبی.' },
        { text: 'سنندج', level: 'medium', description: 'مرکز استان کردستان.' },
        { text: 'ایلام', level: 'medium', description: 'مرکز استان ایلام، واقع در کوهپایه‌های زاگرس.' },
        { text: 'سیرجان', level: 'medium', description: 'شهر مهم در استان کرمان و مرکز تولید پسته.' },
        { text: 'خرمشهر', level: 'medium', description: 'بندر مهمی در خوزستان.' },
        { text: 'شوشتر', level: 'medium', description: 'شهری با سازه‌های آبی باستانی.' },
        { text: 'مریوان', level: 'medium', description: 'شهری در کردستان با دریاچه زریبار.' },
        { text: 'نیشابور', level: 'medium', description: 'شهر تاریخی و فرهنگی در خراسان.' },
        { text: 'میبد', level: 'medium', description: 'شهر باستانی نزدیک یزد با قلعه نارین قلعه.' },
        { text: 'دامغان', level: 'medium', description: 'شهری در سمنان، مرکز تولید پسته و خربزه.' },
        { text: 'گناوه', level: 'medium', description: 'بندر در استان بوشهر.' },
        { text: 'خرم‌آباد', level: 'medium', description: 'مرکز استان لرستان.' },
        { text: 'قزوین', level: 'medium', description: 'شهری تاریخی با کاخ چهل‌ستون.' },
        { text: 'خوانسار', level: 'medium', description: 'شهری در اصفهان معروف به عسل طبیعی.' },
        { text: 'رامسر', level: 'medium', description: 'شهر ساحلی و کوهستانی در مازندران.' },
        { text: 'متل قو', level: 'medium', description: 'منطقه توریستی در مازندران.' },
        { text: 'تنکابن', level: 'medium', description: 'شهری در غرب مازندران.' },
        { text: 'ساوه', level: 'medium', description: 'شهری تاریخی در استان مرکزی.' },
        { text: 'سرعین', level: 'medium', description: 'شهر چشمه‌های آب گرم در اردبیل.' },
        { text: 'کاشمر', level: 'medium', description: 'شهری در استان خراسان رضوی.' },
        { text: 'قروه', level: 'medium', description: 'شهری در استان کردستان.' },
        { text: 'بجنورد', level: 'medium', description: 'مرکز استان خراسان شمالی.' },
        { text: 'بوشهر', level: 'medium', description: 'بندر جنوبی و گرم.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'بندرعباس', level: 'hard', description: 'بندر بزرگ و استراتژیک ایران در کنار خلیج فارس.' },
        { text: 'خوزستان', level: 'hard', description: 'استان گرم و نفتی در جنوب غربی ایران.' },
        { text: 'مازندران', level: 'hard', description: 'استان شمالی ایران، دارای دریا و جنگل.' },
        { text: 'کردستان', level: 'hard', description: 'استان غربی ایران با فرهنگ غنی کردی.' },
        { text: 'خراسان رضوی', level: 'hard', description: 'استان بزرگ ایران که مشهد در آن واقع است.' },
        { text: 'چهارمحال بختیاری', level: 'hard', description: 'استان مرتفع و کوهستانی در مرکز ایران.' },
        { text: 'دریای خزر', level: 'hard', description: 'بزرگترین دریاچه جهان که در شمال ایران قرار دارد.' },
        { text: 'خلیج فارس', level: 'hard', description: 'آبراه استراتژیک در جنوب ایران.' },
        { text: 'کوه‌های البرز', level: 'hard', description: 'رشته کوه بزرگ در شمال ایران.' },
        { text: 'کوه‌های زاگرس', level: 'hard', description: 'رشته کوه بزرگ در غرب ایران.' },
        { text: 'ارگ بم', level: 'hard', description: 'بزرگترین سازه خشتی جهان.' },
        { text: 'میدان نقش جهان', level: 'hard', description: 'میدان تاریخی بزرگ در اصفهان.' },
        { text: 'تخت جمشید', level: 'hard', description: 'بنای باستانی دوره هخامنشی در فارس.' },
        { text: 'نقش رستم', level: 'hard', description: 'آرامگاه شاهان هخامنشی و ساسانی در فارس.' },
        { text: 'جزیره ابوموسی', level: 'hard', description: 'جزیره‌ای استراتژیک در خلیج فارس.' },
        { text: 'دریاچه ارومیه', level: 'hard', description: 'بزرگترین دریاچه نمکی ایران.' },
        { text: 'دهلران', level: 'hard', description: 'شهری در ایلام با منابع نفت و گاز.' },
        { text: 'بندر انزلی', level: 'hard', description: 'بندر مهم در استان گیلان.' },
        { text: 'آرامگاه حافظ', level: 'hard', description: 'محل دفن شاعر بزرگ، حافظ در شیراز.' },
        { text: 'باغ ارم', level: 'hard', description: 'باغ تاریخی زیبا در شیراز.' },
        { text: 'آتشکده یزد', level: 'hard', description: 'محل نگهداری آتش مقدس زرتشتیان.' },
        { text: 'گنبد سلطانیه', level: 'hard', description: 'گنبد تاریخی بزرگ در زنجان.' },
        { text: 'پل خواجو', level: 'hard', description: 'پل تاریخی روی زاینده‌رود در اصفهان.' },
        { text: 'مقبره کوروش', level: 'hard', description: 'آرامگاه بنیانگذار سلسله هخامنشی در پاسارگاد.' },
        { text: 'تنگه هرمز', level: 'hard', description: 'گذرگاه استراتژیک بین خلیج فارس و دریای عمان.' },
        { text: 'کویر لوت', level: 'hard', description: 'بیابان بزرگ و خشک در جنوب شرقی ایران.' },
        { text: 'جزیره هنگام', level: 'hard', description: 'جزیره‌ای کوچک در نزدیکی قشم.' },
        { text: 'غار علیصدر', level: 'hard', description: 'بزرگترین غار آبی ایران در همدان.' },
        { text: 'دروازه قرآن', level: 'hard', description: 'طاق تاریخی ورودی شهر شیراز.' },
        { text: 'مجموعه گنجعلیخان', level: 'hard', description: 'مجموعه تاریخی در کرمان شامل حمام و بازار.' },
        { text: 'مراغه', level: 'hard', description: 'شهری تاریخی در آذربایجان شرقی با رصدخانه.' },
        { text: 'بندر گناوه', level: 'hard', description: 'بندر معروف به تجارت.' },
        { text: 'چهل ستون', level: 'hard', description: 'کاخ تاریخی در اصفهان.' },
        { text: 'میدان آزادی', level: 'hard', description: 'معروف‌ترین میدان تهران.' },
      ],
    },
    // ====================================================================================================================
    // === ۴. رنگ‌ها (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'رنگ ها',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'قرمز', level: 'easy', description: 'رنگ خون و آتش، نماد عشق یا خطر.' },
        { text: 'آبی', level: 'easy', description: 'رنگ آسمان و دریا، نماد آرامش.' },
        { text: 'سبز', level: 'easy', description: 'رنگ طبیعت و گیاهان، نماد رشد.' },
        { text: 'زرد', level: 'easy', description: 'رنگ خورشید، نماد شادی.' },
        { text: 'بنفش', level: 'easy', description: 'رنگ سلطنت و رازآلودگی.' },
        { text: 'مشکی', level: 'easy', description: 'تاریک‌ترین رنگ، نماد قدرت.' },
        { text: 'سفید', level: 'easy', description: 'روشن‌ترین رنگ، نماد پاکی.' },
        { text: 'صورتی', level: 'easy', description: 'رنگ محبوبی که اغلب با لطافت مرتبط است.' },
        { text: 'قهوه ای', level: 'easy', description: 'رنگ زمین و چوب، نماد سادگی.' },
        { text: 'عنابی', level: 'easy', description: 'رنگ قرمز تیره شبیه به میوه عناب.' },
        { text: 'نیلی', level: 'easy', description: 'سایه‌ای عمیق از آبی-بنفش.' },
        { text: 'کرمی', level: 'easy', description: 'رنگ زرد روشن و مایل به سفید.' },
        { text: 'بژ', level: 'easy', description: 'رنگ خنثی، روشن و قهوه‌ای مایل به زرد.' },
        { text: 'یشمی', level: 'easy', description: 'سایه‌ای تیره از سبز، شبیه سنگ یشم.' },
        { text: 'نقره ای', level: 'easy', description: 'رنگ فلزی روشن و درخشان.' },
        { text: 'طلایی', level: 'easy', description: 'رنگ درخشان و متالیک شبیه طلا.' },
        { text: 'شتری', level: 'easy', description: 'رنگ قهوه‌ای روشن مایل به زرد.' },
        { text: 'لاکی', level: 'easy', description: 'رنگ قرمز تند و براق.' },
        { text: 'سربی', level: 'easy', description: 'رنگ خاکستری تیره شبیه فلز سرب.' },
        { text: 'مرجانی', level: 'easy', description: 'رنگی بین صورتی و نارنجی.' },
        { text: 'زرین', level: 'easy', description: 'به معنی طلایی.' },
        { text: 'فندقی', level: 'easy', description: 'رنگ قهوه‌ای روشن شبیه فندق.' },
        { text: 'سیر', level: 'easy', description: 'به معنای تیره و عمیق (در مورد رنگ‌ها).' },
        { text: 'روشن', level: 'easy', description: 'به معنای پرنور و کم‌رنگ (در مورد رنگ‌ها).' },
        { text: 'تیره', level: 'easy', description: 'به معنای کم‌نور و عمیق (در مورد رنگ‌ها).' },
        { text: 'مات', level: 'easy', description: 'بی‌درخشش و کدر.' },
        { text: 'برا', level: 'easy', description: 'براق و درخشان.' },
        { text: 'قناری', level: 'easy', description: 'رنگ زرد روشن و شفاف.' },
        { text: 'کاکائویی', level: 'easy', description: 'رنگ قهوه‌ای متوسط شبیه پودر کاکائو.' },
        { text: 'مسی', level: 'easy', description: 'رنگ قرمز مایل به قهوه‌ای شبیه فلز مس.' },
        { text: 'زنگی', level: 'easy', description: 'رنگ تیره و تقریباً سیاه.' },
        { text: 'گندمی', level: 'easy', description: 'رنگ زرد مایل به قهوه‌ای روشن.' },
        { text: 'زیتونی', level: 'easy', description: 'سایه‌ای مات و تیره از سبز مایل به قهوه‌ای.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'نارنجی', level: 'medium', description: 'ترکیبی از قرمز و زرد، رنگ پرتقال.' },
        { text: 'خاکستری', level: 'medium', description: 'ترکیبی از سیاه و سفید، نماد بی‌طرفی.' },
        { text: 'زرشکی', level: 'medium', description: 'سایه‌ای تیره و غنی از قرمز.' },
        { text: 'سرمه ای', level: 'medium', description: 'یک سایه تیره از آبی که به سیاه نزدیک است.' },
        { text: 'لاجوردی', level: 'medium', description: 'سایه‌ای عمیق از آبی.' },
        { text: 'یاسی', level: 'medium', description: 'رنگ روشن و ملایمی از بنفش.' },
        { text: 'بادمجانی', level: 'medium', description: 'رنگ بنفش تیره شبیه پوست بادمجان.' },
        { text: 'فندقی', level: 'medium', description: 'رنگ قهوه‌ای روشن شبیه مغز فندق.' },
        { text: 'زغالی', level: 'medium', description: 'رنگ سیاه مایل به خاکستری.' },
        { text: 'گلی', level: 'medium', description: 'رنگ قرمز مایل به صورتی.' },
        { text: 'جیگری', level: 'medium', description: 'سایه‌ای تیره و عمیق از قرمز که به جگر می‌ماند.' },
        { text: 'آسمانی', level: 'medium', description: 'رنگ آبی روشن شبیه آسمان صاف.' },
        { text: 'ارغوانی', level: 'medium', description: 'رنگی بین قرمز و بنفش.' },
        { text: 'کاهی', level: 'medium', description: 'رنگ زرد روشن شبیه کاه خشک.' },
        { text: 'شکلاتی', level: 'medium', description: 'سایه‌ای تیره و غنی از قهوه‌ای.' },
        { text: 'لیمویی', level: 'medium', description: 'رنگ زرد روشن و تند.' },
        { text: 'سبز پسته ای', level: 'medium', description: 'رنگ سبز روشن شبیه مغز پسته.' },
        { text: 'زردچوبه ای', level: 'medium', description: 'رنگ زرد تند شبیه ادویه زردچوبه.' },
        { text: 'نخودی', level: 'medium', description: 'رنگ بژ مایل به زرد.' },
        { text: 'گردویی', level: 'medium', description: 'رنگ قهوه‌ای تیره شبیه پوست گردو.' },
        { text: 'برنزی', level: 'medium', description: 'رنگ فلزی مایل به قهوه‌ای و طلایی.' },
        { text: 'سفید صدفی', level: 'medium', description: 'سفیدی براق و مایل به صورتی.' },
        { text: 'زیتونی تیره', level: 'medium', description: 'سایه‌ای تیره از رنگ زیتونی.' },
        { text: 'سبز یشمی', level: 'medium', description: 'سایه‌ای عمیق و پررنگ از سبز.' },
        { text: 'آبی روشن', level: 'medium', description: 'آبی کم‌رنگ و ملایم.' },
        { text: 'آبی تیره', level: 'medium', description: 'آبی پررنگ و عمیق.' },
        { text: 'قرمز تند', level: 'medium', description: 'قرمز بسیار پررنگ و روشن.' },
        { text: 'بنفش روشن', level: 'medium', description: 'بنفش کم‌رنگ و ملایم.' },
        { text: 'پوست پیازی', level: 'medium', description: 'رنگ صورتی مایل به قهوه‌ای.' },
        { text: 'خردلی', level: 'medium', description: 'رنگ زرد تیره و کمی کدر.' },
        { text: 'قرمز آجری', level: 'medium', description: 'قرمز مایل به قهوه‌ای و تیره.' },
        { text: 'آبی کبود', level: 'medium', description: 'آبی بسیار تیره و عمیق.' },
        { text: 'سفید برفی', level: 'medium', description: 'سفید خالص و درخشان.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'فیروزه ای', level: 'hard', description: 'رنگی بین آبی و سبز که از سنگ فیروزه گرفته شده است.' },
        { text: 'صورتی چرک', level: 'hard', description: 'صورتی کدر و تیره مایل به خاکستری.' },
        { text: 'سبز لجنی', level: 'hard', description: 'سبز کدر و تیره شبیه لجن.' },
        { text: 'قرمز آتشی', level: 'hard', description: 'قرمز بسیار روشن و پرحرارت.' },
        { text: 'قرمز شرابی', level: 'hard', description: 'قرمز تیره و عمیق شبیه شراب.' },
        { text: 'آبی کاربنی', level: 'hard', description: 'آبی بسیار تیره و نزدیک به سیاه.' },
        { text: 'آبی فیروزه ای', level: 'hard', description: 'رنگی روشن بین آبی و سبز.' },
        { text: 'زرد قناری', level: 'hard', description: 'زرد روشن و شفاف شبیه پرنده قناری.' },
        { text: 'آبی نفتی', level: 'hard', description: 'آبی تیره متمایل به سبز.' },
        { text: 'قهوه ای تیره', level: 'hard', description: 'سایه عمیق و پررنگ از قهوه‌ای.' },
        { text: 'آبی پاستلی', level: 'hard', description: 'آبی بسیار روشن و ملایم.' },
        { text: 'سبز نعنایی', level: 'hard', description: 'سبز روشن و خنک شبیه نعناع.' },
        { text: 'سرخابی', level: 'hard', description: 'رنگی تند بین صورتی و قرمز.' },
        { text: 'بنفش سلطنتی', level: 'hard', description: 'بنفش عمیق و غنی که نماد سلطنت است.' },
        { text: 'سفید شیری', level: 'hard', description: 'سفیدی که کمی به زردی می‌زند.' },
        { text: 'آبی خاکستری', level: 'hard', description: 'ترکیبی از آبی و خاکستری.' },
        { text: 'زرد طلایی', level: 'hard', description: 'زرد روشن و درخشان.' },
        { text: 'سبز زمردی', level: 'hard', description: 'سبز پررنگ و عمیق شبیه سنگ زمرد.' },
        { text: 'خرمایی', level: 'hard', description: 'رنگ قهوه‌ای گرم و متوسط.' },
        { text: 'زرد برنزی', level: 'hard', description: 'زرد مایل به قهوه‌ای و متالیک.' },
        { text: 'بیسکویتی', level: 'hard', description: 'رنگ قهوه‌ای روشن شبیه بیسکویت.' },
        { text: 'آبی کبالت', level: 'hard', description: 'آبی روشن و تند.' },
        { text: 'خونی', level: 'hard', description: 'رنگ قرمز تیره شبیه خون.' },
        { text: 'نقره ای کدر', level: 'hard', description: 'نقره‌ای که درخشش خود را از دست داده.' },
        { text: 'عاج فیلی', level: 'hard', description: 'رنگ سفید مایل به زرد روشن.' },
        { text: 'گلبهی', level: 'hard', description: 'رنگی بین صورتی و نارنجی.' },
        { text: 'اُکر', level: 'hard', description: 'رنگ زرد مایل به قهوه‌ای، نوعی رنگدانه طبیعی.' },
        { text: 'آبی اقیانوسی', level: 'hard', description: 'سایه‌ای از آبی که شبیه آب اقیانوس است.' },
        { text: 'قرمز مخملی', level: 'hard', description: 'قرمز عمیق و پررنگ با بافتی نرم.' },
        { text: 'صورتی جیغ', level: 'hard', description: 'صورتی بسیار روشن و تند.' },
        { text: 'بنفش کبود', level: 'hard', description: 'بنفش تیره و مایل به سیاه.' },
        { text: 'آبی دریایی', level: 'hard', description: 'رنگ آبی تیره شبیه عمق دریا.' },
        { text: 'آبی روشن آسمانی', level: 'hard', description: 'رنگ آبی بسیار ملایم و کم‌رنگ.' },
        { text: 'زرد فسفری', level: 'hard', description: 'زرد بسیار روشن و درخشان.' },
      ],
    },
    // ====================================================================================================================
    // === ۵. اشیا و ابزار (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'اشیا و ابزار',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'میز', level: 'easy', description: 'سطحی صاف با پایه برای کار یا غذا.' },
        { text: 'صندلی', level: 'easy', description: 'وسیله‌ای با پشت برای نشستن.' },
        { text: 'کمد', level: 'easy', description: 'جعبه‌ای ایستاده برای نگهداری لباس.' },
        { text: 'آینه', level: 'easy', description: 'سطحی شیشه‌ای که تصویر را منعکس می‌کند.' },
        { text: 'کلید', level: 'easy', description: 'قطعه‌ای فلزی برای باز کردن قفل.' },
        { text: 'قفل', level: 'easy', description: 'مکانیزمی برای بستن درها.' },
        { text: 'لیوان', level: 'easy', description: 'ظرفی برای نوشیدن مایعات.' },
        { text: 'بشقاب', level: 'easy', description: 'سطح گود یا صافی برای سرو غذا.' },
        { text: 'چکش', level: 'easy', description: 'ابزاری برای کوبیدن میخ.' },
        { text: 'اره', level: 'easy', description: 'ابزاری با دندانه‌های تیز برای بریدن چوب.' },
        { text: 'سطل', level: 'easy', description: 'ظرفی برای نگهداری زباله یا مایعات.' },
        { text: 'گلدان', level: 'easy', description: 'ظرفی برای نگهداری گل و گیاه.' },
        { text: 'چراغ', level: 'easy', description: 'منبع نور الکتریکی.' },
        { text: 'باتری', level: 'easy', description: 'منبع انرژی شیمیایی قابل حمل.' },
        { text: 'پریز', level: 'easy', description: 'نقطه‌ای روی دیوار برای اتصال برق.' },
        { text: 'کاغذ', level: 'easy', description: 'ماده‌ای نازک برای نوشتن یا چاپ.' },
        { text: 'کتاب', level: 'easy', description: 'مجموعه‌ای از صفحات نوشته شده.' },
        { text: 'قلم', level: 'easy', description: 'ابزاری برای نوشتن با جوهر.' },
        { text: 'دفتر', level: 'easy', description: 'مجموعه‌ای از کاغذها برای یادداشت‌برداری.' },
        { text: 'پتو', level: 'easy', description: 'پارچه‌ای ضخیم برای گرم نگه داشتن.' },
        { text: 'بالش', level: 'easy', description: 'کیسه‌ای نرم برای زیر سر.' },
        { text: 'جوراب', level: 'easy', description: 'پوششی برای پا.' },
        { text: 'کفش', level: 'easy', description: 'پوششی برای محافظت از پا.' },
        { text: 'عینک', level: 'easy', description: 'وسیله‌ای برای بهبود بینایی یا محافظت از چشم.' },
        { text: 'ساعت', level: 'easy', description: 'وسیله‌ای برای نمایش زمان.' },
        { text: 'شمع', level: 'easy', description: 'منبع نور و گرمای قدیمی از موم.' },
        { text: 'کیف', level: 'easy', description: 'جایگاهی برای حمل وسایل.' },
        { text: 'کلاه', level: 'easy', description: 'پوششی برای سر.' },
        { text: 'کاپشن', level: 'easy', description: 'لباس ضخیم برای گرم نگه داشتن بدن.' },
        { text: 'گاز', level: 'easy', description: 'منبع انرژی برای پخت و پز.' },
        { text: 'سیم', level: 'easy', description: 'رشته‌ای فلزی برای انتقال برق یا داده.' },
        { text: 'رژ', level: 'easy', description: 'ماده آرایشی برای لب.' },
        { text: 'تلفن', level: 'easy', description: 'دستگاه ارتباطی سیمی یا بی‌سیم.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'یخچال', level: 'medium', description: 'دستگاهی برای سرد نگه داشتن مواد غذایی.' },
        { text: 'تلویزیون', level: 'medium', description: 'دستگاه الکترونیکی برای تماشای برنامه.' },
        { text: 'آچار', level: 'medium', description: 'ابزاری برای باز و بستن پیچ و مهره.' },
        { text: 'انبردست', level: 'medium', description: 'ابزاری برای گرفتن یا بریدن اجسام.' },
        { text: 'جاروبرقی', level: 'medium', description: 'دستگاهی برای تمیز کردن زمین با مکش.' },
        { text: 'سشوار', level: 'medium', description: 'دستگاه برقی برای خشک کردن مو.' },
        { text: 'قاشق', level: 'medium', description: 'ابزاری فلزی برای خوردن غذا.' },
        { text: 'چنگال', level: 'medium', description: 'ابزاری فلزی برای فرو بردن در غذا.' },
        { text: 'پنجره', level: 'medium', description: 'محفظه‌ای شیشه‌ای در دیوار.' },
        { text: 'فرش', level: 'medium', description: 'پوششی بافته شده برای زمین.' },
        { text: 'ملافه', level: 'medium', description: 'پارچه‌ای نازک برای پوشاندن تشک.' },
        { text: 'پوشه', level: 'medium', description: 'محفظه‌ای برای نگهداری اسناد.' },
        { text: 'ترازو', level: 'medium', description: 'دستگاهی برای اندازه‌گیری وزن.' },
        { text: 'فلاسک', level: 'medium', description: 'ظرفی برای نگهداری مایعات گرم یا سرد.' },
        { text: 'دوش', level: 'medium', description: 'سری پاشنده آب در حمام.' },
        { text: 'لوله', level: 'medium', description: 'مجرا یا مسیری برای عبور مایعات یا گاز.' },
        { text: 'تایر', level: 'medium', description: 'حلقه لاستیکی چرخ خودرو.' },
        { text: 'پدال', level: 'medium', description: 'اهرمی که با پا فشرده می‌شود.' },
        { text: 'دکمه', level: 'medium', description: 'قسمتی از لباس برای بستن.' },
        { text: 'زیپ', level: 'medium', description: 'بستن نواری برای لباس و کیف.' },
        { text: 'دستکش', level: 'medium', description: 'پوششی برای دست.' },
        { text: 'ماژیک', level: 'medium', description: 'قلم با نوک نمدی و جوهر رنگی.' },
        { text: 'برف پاک کن', level: 'medium', description: 'وسیله‌ای برای پاک کردن شیشه جلو خودرو.' },
        { text: 'کبریت', level: 'medium', description: 'چوب کوچک برای روشن کردن آتش.' },
        { text: 'فیلتر', level: 'medium', description: 'وسیله‌ای برای جداسازی مواد ناخواسته.' },
        { text: 'کابل', level: 'medium', description: 'رشته‌ای ضخیم برای انتقال برق یا داده.' },
        { text: 'پلاک', level: 'medium', description: 'صفحه فلزی شناسایی خودرو.' },
        { text: 'لنز', level: 'medium', description: 'قطعه‌ای شیشه‌ای برای متمرکز کردن نور.' },
        { text: 'فرمان', level: 'medium', description: 'چرخی برای هدایت خودرو.' },
        { text: 'آفتابگیر', level: 'medium', description: 'وسیله‌ای برای جلوگیری از تابش نور خورشید.' },
        { text: 'جاکلیدی', level: 'medium', description: 'حلقه‌ای برای نگهداری چندین کلید.' },
        { text: 'روکش', level: 'medium', description: 'پوششی برای محافظت.' },
        { text: 'ماسک', level: 'medium', description: 'پوششی برای صورت برای جلوگیری از آلودگی.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'گوشی همراه', level: 'hard', description: 'دستگاه ارتباطی کوچک با قابلیت تماس و اینترنت.' },
        { text: 'لپ تاپ', level: 'hard', description: 'رایانه شخصی قابل حمل.' },
        { text: 'کتابخانه', level: 'hard', description: 'قفسه‌ای برای نگهداری و سازماندهی کتاب‌ها.' },
        { text: 'قاب عکس', level: 'hard', description: 'محفظه‌ای برای نمایش و محافظت از تصاویر.' },
        { text: 'پیچ گوشتی', level: 'hard', description: 'ابزاری برای چرخاندن پیچ‌ها.' },
        { text: 'ساعت مچی', level: 'hard', description: 'ساعت کوچک که روی مچ دست بسته می‌شود.' },
        { text: 'چراغ قوه', level: 'hard', description: 'منبع نور قابل حمل و دستی.' },
        { text: 'کپسول آتش نشانی', level: 'hard', description: 'وسیله‌ای برای مهار آتش‌سوزی‌های کوچک.' },
        { text: 'ماشین لباسشویی', level: 'hard', description: 'دستگاهی برای شستن لباس.' },
        { text: 'ظرفشویی', level: 'hard', description: 'دستگاهی برای شستن ظروف.' },
        { text: 'پنجره کشویی', level: 'hard', description: 'پنجره‌ای که برای باز و بسته شدن حرکت افقی دارد.' },
        { text: 'پرینتر سه بعدی', level: 'hard', description: 'دستگاهی برای ساخت اشیا سه بعدی.' },
        { text: 'دوربین عکاسی', level: 'hard', description: 'دستگاهی برای ثبت تصاویر ثابت یا متحرک.' },
        { text: 'اسکنر اسناد', level: 'hard', description: 'دستگاهی برای تبدیل تصاویر فیزیکی به دیجیتال.' },
        { text: 'پروژکتور', level: 'hard', description: 'دستگاهی برای نمایش تصاویر روی پرده بزرگ.' },
        { text: 'صفحه کلید', level: 'hard', description: 'مجموعه‌ای از دکمه‌ها برای ورود اطلاعات به رایانه.' },
        { text: 'دیسک سخت', level: 'hard', description: 'تجهیزات ذخیره‌سازی داده‌های اصلی رایانه.' },
        { text: 'کارت حافظه', level: 'hard', description: 'چیپ کوچک برای ذخیره داده‌ها.' },
        { text: 'لوازم آرایشی', level: 'hard', description: 'مواد و وسایل برای زیبایی و آرایش.' },
        { text: 'رادیو پخش', level: 'hard', description: 'دستگاهی برای دریافت و پخش برنامه‌های رادیویی.' },
        { text: 'سیمان', level: 'hard', description: 'ماده‌ای پودری که برای ساخت و ساز استفاده می‌شود.' },
        { text: 'آجر', level: 'hard', description: 'واحد ساختمانی سخت که برای ساخت دیوار استفاده می‌شود.' },
        { text: 'چسب مایع', level: 'hard', description: 'ماده‌ای چسبنده که در حالت مایع است.' },
        { text: 'باند چسب زخم', level: 'hard', description: 'وسیله‌ای برای پوشاندن زخم‌های کوچک.' },
        { text: 'لوله کشی', level: 'hard', description: 'سیستم لوله‌ها برای انتقال آب و گاز.' },
        { text: 'پمپ آب', level: 'hard', description: 'دستگاهی برای انتقال آب از یک نقطه به نقطه دیگر.' },
        { text: 'آبگرمکن گازی', level: 'hard', description: 'دستگاهی برای گرم کردن آب با استفاده از گاز.' },
        { text: 'دریچه فاضلاب', level: 'hard', description: 'پوشش فلزی سنگین روی زمین برای دسترسی به کانال‌های زیرزمینی.' },
        { text: 'توری سیمی', level: 'hard', description: 'شبکه‌ای از سیم‌های نازک.' },
        { text: 'کفپوش چوبی', level: 'hard', description: 'پوشش زمین ساخته شده از چوب.' },
        { text: 'سکه فلزی', level: 'hard', description: 'پول خرد فلزی.' },
        { text: 'میکروسکوپ', level: 'hard', description: 'ابزاری برای دیدن اشیا بسیار کوچک.' },
        { text: 'تلسکوپ', level: 'hard', description: 'ابزاری برای مشاهده اجرام دور در فضا.' },
        { text: 'کولر گازی', level: 'hard', description: 'دستگاهی برای سرمایش اتاق با گاز.' },
      ],
    },
    // ====================================================================================================================
    // === ۶. خوراکی‌ها و غذاها (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'خوراکی ها و غذاها',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'نان', level: 'easy', description: 'غذای اصلی، از آرد گندم تهیه می‌شود.' },
        { text: 'شیر', level: 'easy', description: 'نوشیدنی سفید رنگ و مغذی.' },
        { text: 'ماست', level: 'easy', description: 'فرآورده لبنی از تخمیر شیر.' },
        { text: 'کره', level: 'easy', description: 'فرآورده لبنی چرب از خامه.' },
        { text: 'تخم مرغ', level: 'easy', description: 'ماده غذایی مقوی که توسط مرغ تولید می‌شود.' },
        { text: 'پنیر', level: 'easy', description: 'فرآورده لبنی جامد و شور.' },
        { text: 'عسل', level: 'easy', description: 'ماده شیرین و چسبناک که توسط زنبور تولید می‌شود.' },
        { text: 'پیتزا', level: 'easy', description: 'غذای ایتالیایی با نان گرد و پنیر.' },
        { text: 'شکلات', level: 'easy', description: 'ماده شیرین از دانه کاکائو.' },
        { text: 'آب', level: 'easy', description: 'مایع حیاتی برای زندگی.' },
        { text: 'چای', level: 'easy', description: 'نوشیدنی گرم و پرطرفدار.' },
        { text: 'قهوه', level: 'easy', description: 'نوشیدنی تلخ از دانه قهوه.' },
        { text: 'دلستر', level: 'easy', description: 'نوشیدنی گازدار غیر الکلی.' },
        { text: 'نوشابه', level: 'easy', description: 'نوشیدنی گازدار و شیرین.' },
        { text: 'دوغ', level: 'easy', description: 'نوشیدنی سنتی ایرانی از ماست رقیق شده.' },
        { text: 'کباب', level: 'easy', description: 'گوشت پخته شده روی آتش.' },
        { text: 'کوکو', level: 'easy', description: 'غذایی از سبزی یا سیب زمینی و تخم مرغ.' },
        { text: 'شله', level: 'easy', description: 'آش یا غذای آبکی غلیظ.' },
        { text: 'عدس', level: 'easy', description: 'حبوبات کوچک و گرد.' },
        { text: 'ماش', level: 'easy', description: 'حبوبات کوچک و سبز.' },
        { text: 'لواشک', level: 'easy', description: 'تنقلات ترش و نازک از میوه.' },
        { text: 'بستنی', level: 'easy', description: 'دسر شیرین و سرد.' },
        { text: 'ژله', level: 'easy', description: 'دسر شفاف و لرزان.' },
        { text: 'مربا', level: 'easy', description: 'میوه پخته شده در شکر.' },
        { text: 'سرکه', level: 'easy', description: 'مایع ترش که در ترشی استفاده می‌شود.' },
        { text: 'روغن', level: 'easy', description: 'مایع چرب برای پخت و پز.' },
        { text: 'سس', level: 'easy', description: 'مایع غلیظ برای طعم‌دهی غذا.' },
        { text: 'رب', level: 'easy', description: 'ماده غلیظ از گوجه یا انار.' },
        { text: 'شکر', level: 'easy', description: 'ماده شیرین برای شیرین کردن.' },
        { text: 'نمک', level: 'easy', description: 'ماده شور برای طعم‌دهی.' },
        { text: 'فلفل', level: 'easy', description: 'ادویه تند و معطر.' },
        { text: 'ادویه', level: 'easy', description: 'ماده معطر برای طعم‌دهی غذا.' },
        { text: 'بیسکویت', level: 'easy', description: 'شیرینی ترد و خشک.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'چلو کباب', level: 'medium', description: 'رایج‌ترین غذای رستورانی ایران (برنج و کباب).' },
        { text: 'آش رشته', level: 'medium', description: 'آش غلیظی که با رشته و حبوبات تهیه می‌شود.' },
        { text: 'ماکارونی', level: 'medium', description: 'غذای محبوب با پاستای فرم‌دار.' },
        { text: 'قرمه سبزی', level: 'medium', description: 'خورشت محبوب ایرانی با سبزی سرخ‌شده.' },
        { text: 'قیمه', level: 'medium', description: 'خورشت با لپه، گوشت و سیب زمینی خلالی.' },
        { text: 'جوجو کباب', level: 'medium', description: 'تکه‌های مرغ کباب‌شده.' },
        { text: 'شیربرنج', level: 'medium', description: 'دسر یا صبحانه‌ای از برنج پخته شده در شیر.' },
        { text: 'ته چین', level: 'medium', description: 'غذای پلویی با ماست، تخم مرغ و گوشت.' },
        { text: 'کله پاچه', level: 'medium', description: 'غذای سنتی سنگین از سر و پای گوسفند.' },
        { text: 'کشک', level: 'medium', description: 'فرآورده لبنی ترش و خشک شده.' },
        { text: 'زرشک پلو', level: 'medium', description: 'پلو مخلوط با زرشک و زعفران، اغلب با مرغ.' },
        { text: 'سوپ جو', level: 'medium', description: 'سوپ رقیق با جو و سبزیجات.' },
        { text: 'املت', level: 'medium', description: 'تخم مرغ سرخ شده با گوجه فرنگی.' },
        { text: 'دلمه', level: 'medium', description: 'غذایی از برگ یا سبزیجات شکم‌پر.' },
        { text: 'کتلت', level: 'medium', description: 'ترکیبی از گوشت چرخ‌کرده و سیب زمینی.' },
        { text: 'دسر', level: 'medium', description: 'شیرینی که بعد از غذا سرو می‌شود.' },
        { text: 'کیک', level: 'medium', description: 'شیرینی پف کرده و اسفنجی.' },
        { text: 'نان بربری', level: 'medium', description: 'نان سنتی ایرانی به شکل دراز.' },
        { text: 'نان سنگک', level: 'medium', description: 'نان محبوب ایرانی که روی سنگ داغ پخته می‌شود.' },
        { text: 'نان لواش', level: 'medium', description: 'نان بسیار نازک ایرانی.' },
        { text: 'سوسیس', level: 'medium', description: 'گوشت فرآوری شده در پوشش.' },
        { text: 'فلافل', level: 'medium', description: 'غذای محلی جنوب از نخود سرخ شده.' },
        { text: 'سمبوسه', level: 'medium', description: 'نان مثلثی سرخ‌شده با سیب زمینی و ادویه.' },
        { text: 'حلوا', level: 'medium', description: 'شیرینی سنتی از آرد و شکر.' },
        { text: 'سوهان', level: 'medium', description: 'شیرینی نازک و ترد قم.' },
        { text: 'گز', level: 'medium', description: 'شیرینی سنتی اصفهان از انگبین.' },
        { text: 'پولکی', level: 'medium', description: 'شیرینی نازک شبیه سکه.' },
        { text: 'کلوچه', level: 'medium', description: 'شیرینی گرد با مغز گردو یا نارگیل.' },
        { text: 'کماج', level: 'medium', description: 'نوعی نان یا شیرینی محلی.' },
        { text: 'نقل', level: 'medium', description: 'شیرینی کوچک سفید رنگ.' },
        { text: 'پشمک', level: 'medium', description: 'شیرینی رشته‌ای و نرم.' },
        { text: 'گزینه', level: 'medium', description: 'نوعی شیرینی سنتی.' },
        { text: 'شیرینی کشمشی', level: 'medium', description: 'شیرینی کوچک و گرد با کشمش.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'سالاد شیرازی', level: 'hard', description: 'سالاد محبوب ایرانی با خیار، گوجه، پیاز و آبلیمو.' },
        { text: 'کباب کوبیده', level: 'hard', description: 'گوشت چرخ‌کرده سیخ‌شده روی آتش.' },
        { text: 'عدس پلو', level: 'hard', description: 'غذای پلویی که با عدس، برنج و کشمش تهیه می‌شود.' },
        { text: 'دیزی سنگی', level: 'hard', description: 'خوراک سنتی که در ظرف سنگی پخته می‌شود.' },
        { text: 'کشک بادمجان', level: 'hard', description: 'پیش‌غذای ایرانی از بادمجان سرخ شده به همراه کشک.' },
        { text: 'باقالی پلو', level: 'hard', description: 'پلوی مخلوطی با باقالی سبز و شوید.' },
        { text: 'شله زرد', level: 'hard', description: 'دسر سنتی ایرانی از برنج و زعفران و شکر.' },
        { text: 'خورشت فسنجان', level: 'hard', description: 'خورشت شیرین و ترش ایرانی با رب انار و گردو.' },
        { text: 'کباب برگ', level: 'hard', description: 'گوشت راسته گوسفند یا گوساله به صورت ورقه‌ای کباب شده.' },
        { text: 'میرزاقاسمی', level: 'hard', description: 'غذای گیلانی از بادمجان کبابی، گوجه و تخم مرغ.' },
        { text: 'غذاهای دریایی', level: 'hard', description: 'غذاهایی که از ماهی، میگو و سایر آبزیان تهیه می‌شوند.' },
        { text: 'ساندویچ', level: 'hard', description: 'غذایی که بین دو تکه نان سرو می‌شود.' },
        { text: 'دونات', level: 'hard', description: 'شیرینی حلقه‌ای سرخ شده و شیرین.' },
        { text: 'لازانیا', level: 'hard', description: 'غذای ایتالیایی با لایه‌های پاستا و سس گوشت.' },
        { text: 'سوپ شیر', level: 'hard', description: 'سوپی که با شیر و جو تهیه می‌شود.' },
        { text: 'شربت آلبالو', level: 'hard', description: 'نوشیدنی خنک و ترش از عصاره آلبالو.' },
        { text: 'نان شیرمال', level: 'hard', description: 'نان شیرین و نرم ایرانی.' },
        { text: 'حلوا شکری', level: 'hard', description: 'شیرینی صبحانه از ارده و شکر.' },
        { text: 'پنیر لیقوان', level: 'hard', description: 'پنیر سنتی گوسفندی با طعم شور و تند.' },
        { text: 'ماست موسیر', level: 'hard', description: 'ماست مخلوط با سبزی موسیر.' },
        { text: 'کشک بادمجان', level: 'hard', description: 'پیش‌غذای ایرانی از بادمجان سرخ شده و کشک.' },
        { text: 'سبزی پلو با ماهی', level: 'hard', description: 'غذای شب عید ایرانی.' },
        { text: 'آبگوشت بزباش', level: 'hard', description: 'نوعی آبگوشت با گوشت، سبزیجات و لوبیا.' },
        { text: 'میرزاقاسمی', level: 'hard', description: 'غذای محلی گیلان با بادمجان و گوجه.' },
        { text: 'باقلا قاتق', level: 'hard', description: 'خورشت گیلانی با باقالی و شوید.' },
        { text: 'کوفته تبریزی', level: 'hard', description: 'کوفته بزرگ و پر شده از گوشت و سبزیجات.' },
        { text: 'اشکنه تخم مرغ', level: 'hard', description: 'نوعی آبگوشت ساده با نان و تخم مرغ.' },
        { text: 'کله جوش', level: 'hard', description: 'غذایی سریع با کشک و پیاز داغ.' },
        { text: 'آب دوغ خیار', level: 'hard', description: 'غذای سرد تابستانی با دوغ، خیار و کشمش.' },
        { text: 'کیک یزدی', level: 'hard', description: 'شیرینی ساده و سنتی که در شهر یزد تهیه می‌شود.' },
        { text: 'نان خامه ای', level: 'hard', description: 'نان گرد شیرین پر شده با خامه.' },
        { text: 'قند کله', level: 'hard', description: 'قند به صورت توده بزرگ و قالبی.' },
        { text: 'عرق نعنا', level: 'hard', description: 'نوشیدنی سنتی از عرق‌گیری نعناع.' },
        { text: 'ساندویچ هات داگ', level: 'hard', description: 'سوسیس سرخ شده در نان باگت.' },
      ],
    },
    // ====================================================================================================================
    // === ۷. فن آوری و علوم (۱۰۰ کلمه) - توزیع بر اساس طول کلمه ===
    // ====================================================================================================================
    {
      name: 'فن آوری و علوم',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'رایانه', level: 'easy', description: 'ماشینی برای پردازش داده‌ها.' },
        { text: 'لنز', level: 'easy', description: 'قطعه‌ای شیشه‌ای برای متمرکز کردن نور.' },
        { text: 'تراشه', level: 'easy', description: 'مدار مجتمع کوچک و مهم.' },
        { text: 'وب', level: 'easy', description: 'مخفف شبکه جهانی وب (World Wide Web).' },
        { text: 'فضا', level: 'easy', description: 'فضای بی‌نهایت در خارج از زمین.' },
        { text: 'دارو', level: 'easy', description: 'ماده‌ای برای درمان بیماری.' },
        { text: 'ژن', level: 'easy', description: 'واحد وراثت در موجودات زنده.' },
        { text: 'هسته', level: 'easy', description: 'مرکز اتم یا سلول.' },
        { text: 'گرافیک', level: 'easy', description: 'هنر نمایش بصری داده‌ها.' },
        { text: 'برق', level: 'easy', description: 'جریان الکتریکی.' },
        { text: 'صوت', level: 'easy', description: 'امواج قابل شنیدن.' },
        { text: 'لرزه', level: 'easy', description: 'تکان‌های زمین.' },
        { text: 'فیزیک', level: 'easy', description: 'علم مطالعه ماده، انرژی و حرکت.' },
        { text: 'شیمی', level: 'easy', description: 'علم مطالعه مواد و ترکیب آن‌ها.' },
        { text: 'زیست', level: 'easy', description: 'علم مطالعه موجودات زنده.' },
        { text: 'فیلتر', level: 'easy', description: 'وسیله‌ای برای جداسازی مواد.' },
        { text: 'باند', level: 'easy', description: 'محدوده فرکانسی.' },
        { text: 'نویز', level: 'easy', description: 'صدای مزاحم و ناخواسته.' },
        { text: 'مدار', level: 'easy', description: 'مسیر بسته برای عبور جریان یا سیگنال.' },
        { text: 'باطری', level: 'easy', description: 'منبع انرژی شیمیایی.' },
        { text: 'داده', level: 'easy', description: 'اطلاعات خام.' },
        { text: 'الگو', level: 'easy', description: 'ساختار تکراری.' },
        { text: 'ربات', level: 'easy', description: 'ماشین برنامه‌ریزی شده.' },
        { text: 'پالس', level: 'easy', description: 'سیگنال کوتاه و سریع.' },
        { text: 'فرکانس', level: 'easy', description: 'تعداد تکرار یک واقعه در واحد زمان.' },
        { text: 'سرور', level: 'easy', description: 'رایانه‌ای که خدمات ارائه می‌دهد.' },
        { text: 'دامنه', level: 'easy', description: 'نام آدرس یک وب‌سایت.' },
        { text: 'فایروال', level: 'easy', description: 'سیستم امنیتی که ترافیک شبکه را کنترل می‌کند.' },
        { text: 'اسکنر', level: 'easy', description: 'دستگاهی برای تبدیل تصویر به دیجیتال.' },
        { text: 'ماوس', level: 'easy', description: 'وسیله ورودی برای کنترل مکان نما.' },
        { text: 'کد', level: 'easy', description: 'مجموعه‌ای از دستورالعمل‌ها.' },
        { text: 'پیکسل', level: 'easy', description: 'کوچکترین عنصر تصویر دیجیتال.' },
        { text: 'گسل', level: 'easy', description: 'شکاف در پوسته زمین.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'برنامه نویسی', level: 'medium', description: 'فرآیند نوشتن دستورالعمل برای کامپیوتر.' },
        { text: 'هوش مصنوعی', level: 'medium', description: 'توانایی ماشین‌ها برای تقلید از هوش انسان.' },
        { text: 'وب سایت', level: 'medium', description: 'مجموعه‌ای از صفحات وب مرتبط.' },
        { text: 'پردازنده', level: 'medium', description: 'مغز رایانه که دستورات را اجرا می‌کند.' },
        { text: 'بلاکچین', level: 'medium', description: 'دفتر کل توزیع شده و غیرمتمرکز.' },
        { text: 'رمزنگاری', level: 'medium', description: 'فرآیند تبدیل اطلاعات به کدی محرمانه.' },
        { text: 'پهپاد', level: 'medium', description: 'هواپیمای بدون سرنشین هدایت از راه دور.' },
        { text: 'ماهواره', level: 'medium', description: 'وسیله‌ای که به دور زمین می‌چرخد و سیگنال می‌فرستد.' },
        { text: 'تلسکوپ', level: 'medium', description: 'ابزاری برای مشاهده اجرام دور در فضا.' },
        { text: 'میکروسکوپ', level: 'medium', description: 'ابزاری برای دیدن اشیا بسیار کوچک.' },
        { text: 'الگوریتم', level: 'medium', description: 'مجموعه‌ای از دستورالعمل‌ها برای حل یک مشکل.' },
        { text: 'رابط کاربری', level: 'medium', description: 'نقطه‌ای که کاربر با دستگاه تعامل می‌کند.' },
        { text: 'پادکست', level: 'medium', description: 'فایل صوتی دیجیتال قابل دانلود.' },
        { text: 'موتور جت', level: 'medium', description: 'نوعی موتور که با خروج گازهای داغ، پیشرانش ایجاد می‌کند.' },
        { text: 'نیروگاه', level: 'medium', description: 'محلی برای تولید برق.' },
        { text: 'ژئوفیزیک', level: 'medium', description: 'علم مطالعه ویژگی‌های فیزیکی زمین.' },
        { text: 'متافیزیک', level: 'medium', description: 'علم مطالعه مفاهیم فراتر از طبیعت.' },
        { text: 'بیوشیمی', level: 'medium', description: 'علم مطالعه فرآیندهای شیمیایی در موجودات زنده.' },
        { text: 'هیدرولیک', level: 'medium', description: 'علم استفاده از مایعات برای انتقال نیرو.' },
        { text: 'ترمودینامیک', level: 'medium', description: 'علم مطالعه رابطه بین گرما و کار.' },
        { text: 'فناوری', level: 'medium', description: 'کاربرد دانش علمی برای اهداف عملی.' },
        { text: 'کیت', level: 'medium', description: 'مجموعه‌ای از ابزارها و قطعات.' },
        { text: 'لابراتوار', level: 'medium', description: 'آزمایشگاه علمی.' },
        { text: 'سنسور', level: 'medium', description: 'دستگاهی برای تشخیص تغییرات محیط.' },
        { text: 'بیومتریک', level: 'medium', description: 'فناوری شناسایی افراد بر اساس ویژگی‌های بیولوژیکی.' },
        { text: 'ترانزیستور', level: 'medium', description: 'قطعه‌ای الکترونیکی که سیگنال را تقویت یا سوئیچ می‌کند.' },
        { text: 'آنتی ویروس', level: 'medium', description: 'نرم‌افزاری برای محافظت در برابر بدافزار.' },
        { text: 'صفحه نمایش', level: 'medium', description: 'سطحی برای نمایش اطلاعات بصری.' },
        { text: 'سیستم عامل', level: 'medium', description: 'نرم‌افزار پایه که منابع رایانه را مدیریت می‌کند.' },
        { text: 'پایگاه داده', level: 'medium', description: 'مجموعه‌ای سازمان‌یافته از داده‌ها.' },
        { text: 'یادگیری عمیق', level: 'medium', description: 'نوع پیشرفته یادگیری ماشین.' },
        { text: 'شبکه عصبی', level: 'medium', description: 'مدل محاسباتی الهام گرفته از مغز.' },
        { text: 'واقعیت مجازی', level: 'medium', description: 'شبیه‌سازی یک محیط سه‌بعدی توسط کامپیوتر.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'اینترنت پر سرعت', level: 'hard', description: 'اتصال سریع به شبکه جهانی وب.' },
        { text: 'یادگیری ماشین', level: 'hard', description: 'زیرمجموعه‌ای از هوش مصنوعی که به کامپیوترها اجازه یادگیری می‌دهد.' },
        { text: 'سامانه توزیع شده', level: 'hard', description: 'سیستمی که اجزای آن روی کامپیوترهای مختلف در یک شبکه قرار دارند.' },
        { text: 'واقعیت افزوده', level: 'hard', description: 'ترکیب دنیای واقعی با عناصر مجازی از طریق دوربین.' },
        { text: 'امنیت سایبری', level: 'hard', description: 'حفاظت از سیستم‌ها و شبکه‌ها در برابر حملات دیجیتالی.' },
        { text: 'رایانش ابری', level: 'hard', description: 'ارائه خدمات محاسباتی از طریق اینترنت.' },
        { text: 'اینترنت اشیا', level: 'hard', description: 'شبکه‌ای از اشیای فیزیکی که به اینترنت متصل هستند.' },
        { text: 'نانوتکنولوژی', level: 'hard', description: 'علم کار با مواد در سطح اتمی و مولکولی.' },
        { text: 'مهندسی ژنتیک', level: 'hard', description: 'دستکاری ژن‌ها برای تغییر ویژگی‌های موجودات زنده.' },
        { text: 'داده‌های بزرگ', level: 'hard', description: 'حجم عظیمی از داده که تحلیل آن با روش‌های سنتی دشوار است.' },
        { text: 'پروتکل اینترنت', level: 'hard', description: 'مجموعه‌ای از قوانین برای ارسال داده‌ها در اینترنت.' },
        { text: 'واقعیت ترکیبی', level: 'hard', description: 'ادغام دنیای واقعی و مجازی برای ایجاد محیط‌های جدید.' },
        { text: 'انرژی تجدید پذیر', level: 'hard', description: 'منابع انرژی که به طور طبیعی دوباره پر می‌شوند (مانند خورشید و باد).' },
        { text: 'انفجار بزرگ', level: 'hard', description: 'مدل کیهان‌شناسی که آغاز جهان را توصیف می‌کند.' },
        { text: 'نسبیت عام', level: 'hard', description: 'نظریه گرانش توسط انیشتین.' },
        { text: 'مکانیک کوانتومی', level: 'hard', description: 'علم مطالعه رفتار ماده در مقیاس اتمی و زیراتمی.' },
        { text: 'سلول خورشیدی', level: 'hard', description: 'دستگاهی برای تبدیل نور خورشید به برق.' },
        { text: 'فناوری نانو', level: 'hard', description: 'کاربرد علوم در ابعاد بسیار کوچک.' },
        { text: 'ریاضیات کاربردی', level: 'hard', description: 'استفاده از ریاضیات برای حل مسائل عملی.' },
        { text: 'تکنولوژی آموزشی', level: 'hard', description: 'استفاده از فناوری در فرآیند یادگیری.' },
        { text: 'مهندسی هوافضا', level: 'hard', description: 'طراحی، ساخت و آزمایش هواپیما و فضاپیما.' },
        { text: 'نوروفیدبک', level: 'hard', description: 'روشی برای آموزش مغز برای تنظیم فعالیت خود.' },
        { text: 'ماشین حساب', level: 'hard', description: 'دستگاهی برای انجام محاسبات ریاضی.' },
        { text: 'حافظه موقت', level: 'hard', description: 'حافظه کوتاه مدت رایانه (RAM).' },
        { text: 'پوشه رمزگذاری شده', level: 'hard', description: 'فایلی که برای محافظت، محتوایش تغییر داده شده است.' },
        { text: 'شناسایی الگو', level: 'hard', description: 'فرآیند تشخیص الگوها در داده‌ها.' },
        { text: 'موتور جستجو', level: 'hard', description: 'ابزاری که اطلاعات موجود در وب را پیدا می‌کند.' },
        { text: 'تراکنش دیجیتال', level: 'hard', description: 'انتقال پول به صورت الکترونیکی.' },
        { text: 'رایانش کوانتومی', level: 'hard', description: 'استفاده از مکانیک کوانتومی برای انجام محاسبات.' },
        { text: 'تجارت الکترونیک', level: 'hard', description: 'خرید و فروش کالاها و خدمات از طریق اینترنت.' },
        { text: 'بدافزار جاسوسی', level: 'hard', description: 'نرم‌افزار مخرب برای سرقت اطلاعات.' },
        { text: 'شبکه کامپیوتری', level: 'hard', description: 'اتصال چندین رایانه برای اشتراک منابع.' },
        { text: 'نرم افزار متن باز', level: 'hard', description: 'نرم‌افزاری که کد منبع آن برای عموم در دسترس است.' },
        { text: 'ربات‌های نانو', level: 'hard', description: 'ربات‌هایی با ابعاد بسیار کوچک در سطح نانو.' },
      ],
    },
    // ====================================================================================================================
    // === ۸. مشاغل و حرفه‌ها (۱۰۰ کلمه) - دسته‌بندی جدید ===
    // ====================================================================================================================
    {
      name: 'مشاغل و حرفه ها',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'معلم', level: 'easy', description: 'فردی که به دانش‌آموزان آموزش می‌دهد.' },
        { text: 'پزشک', level: 'easy', description: 'فردی که بیماران را درمان می‌کند.' },
        { text: 'نقاش', level: 'easy', description: 'فردی که نقاشی می‌کند یا دیوارها را رنگ می‌زند.' },
        { text: 'آشپز', level: 'easy', description: 'فردی که غذا تهیه می‌کند.' },
        { text: 'خیاط', level: 'easy', description: 'فردی که لباس می‌دوزد.' },
        { text: 'فروشنده', level: 'easy', description: 'فردی که کالا یا خدمات می‌فروشد.' },
        { text: 'خلبان', level: 'easy', description: 'فردی که هواپیما را هدایت می‌کند.' },
        { text: 'بازیگر', level: 'easy', description: 'فردی که در فیلم یا تئاتر نقش ایفا می‌کند.' },
        { text: 'خبرنگار', level: 'easy', description: 'فردی که خبرها را جمع‌آوری و منتشر می‌کند.' },
        { text: 'باغبان', level: 'easy', description: 'فردی که از باغ و گل و گیاه نگهداری می‌کند.' },
        { text: 'وکیل', level: 'easy', description: 'فردی که مشاوره حقوقی می‌دهد.' },
        { text: 'قاضی', level: 'easy', description: 'فردی که در دادگاه حکم صادر می‌کند.' },
        { text: 'شاعر', level: 'easy', description: 'فردی که شعر می‌سراید.' },
        { text: 'نویسنده', level: 'easy', description: 'فردی که کتاب یا مقاله می‌نویسد.' },
        { text: 'مکانیک', level: 'easy', description: 'فردی که خودروها را تعمیر می‌کند.' },
        { text: 'نجار', level: 'easy', description: 'فردی که با چوب کار می‌کند.' },
        { text: 'بنا', level: 'easy', description: 'فردی که ساختمان می‌سازد.' },
        { text: 'سرباز', level: 'easy', description: 'فردی که در ارتش خدمت می‌کند.' },
        { text: 'نگهبان', level: 'easy', description: 'فردی که از یک مکان مراقبت می‌کند.' },
        { text: 'پاکبان', level: 'easy', description: 'فردی که خیابان‌ها را تمیز می‌کند.' },
        { text: 'حسابدار', level: 'easy', description: 'فردی که امور مالی و حساب‌ها را مدیریت می‌کند.' },
        { text: 'مهندس', level: 'easy', description: 'فردی که با دانش فنی، طرح‌ها را اجرا می‌کند.' },
        { text: 'کارگر', level: 'easy', description: 'فردی که کار فیزیکی انجام می‌دهد.' },
        { text: 'راننده', level: 'easy', description: 'فردی که وسیله نقلیه را هدایت می‌کند.' },
        { text: 'ورزشکار', level: 'easy', description: 'فردی که به صورت حرفه‌ای ورزش می‌کند.' },
        { text: 'کتابدار', level: 'easy', description: 'فردی که در کتابخانه کار می‌کند.' },
        { text: 'صیاد', level: 'easy', description: 'فردی که ماهی یا حیوانات دریایی می‌گیرد.' },
        { text: 'چوپان', level: 'easy', description: 'فردی که از گوسفندان مراقبت می‌کند.' },
        { text: 'ماهیگیر', level: 'easy', description: 'فردی که ماهی صید می‌کند.' },
        { text: 'آرایشگر', level: 'easy', description: 'فردی که مو و صورت را آرایش می‌کند.' },
        { text: 'گارسون', level: 'easy', description: 'فردی که در رستوران غذا سرو می‌کند.' },
        { text: 'نقشه کش', level: 'easy', description: 'فردی که نقشه‌های فنی را طراحی می‌کند.' },
        { text: 'سفیر', level: 'easy', description: 'نماینده یک کشور در کشور دیگر.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'برنامه نویس', level: 'medium', description: 'فردی که کد کامپیوتری می‌نویسد.' },
        { text: 'معمار', level: 'medium', description: 'فردی که طرح ساختمان‌ها را می‌کشد.' },
        { text: 'صنعتگر', level: 'medium', description: 'فردی که با دست، اشیا هنری یا کاربردی می‌سازد.' },
        { text: 'متخصص', level: 'medium', description: 'فردی با دانش عمیق در یک زمینه خاص.' },
        { text: 'روانشناس', level: 'medium', description: 'فردی که رفتار و ذهن انسان را مطالعه می‌کند.' },
        { text: 'دندانپزشک', level: 'medium', description: 'پزشکی که دندان‌ها را درمان می‌کند.' },
        { text: 'دامپزشک', level: 'medium', description: 'پزشکی که حیوانات را درمان می‌کند.' },
        { text: 'داروساز', level: 'medium', description: 'فردی که داروها را تهیه و توزیع می‌کند.' },
        { text: 'مترجم', level: 'medium', description: 'فردی که متون را از زبانی به زبان دیگر برمی‌گرداند.' },
        { text: 'مربی', level: 'medium', description: 'فردی که به دیگران آموزش یا راهنمایی می‌دهد.' },
        { text: 'آتشنشان', level: 'medium', description: 'فردی که برای خاموش کردن آتش و نجات جان تلاش می‌کند.' },
        { text: 'پلیس', level: 'medium', description: 'فردی که مسئول اجرای قانون است.' },
        { text: 'سرآشپز', level: 'medium', description: 'فردی که مسئول اصلی آشپزخانه رستوران است.' },
        { text: 'عکاس', level: 'medium', description: 'فردی که با دوربین عکس می‌گیرد.' },
        { text: 'فیلمساز', level: 'medium', description: 'فردی که فیلم می‌سازد.' },
        { text: 'روزنامه نگار', level: 'medium', description: 'فردی که برای روزنامه یا رسانه خبر می‌نویسد.' },
        { text: 'صداگذار', level: 'medium', description: 'فردی که مسئول میکس صداها در یک پروژه است.' },
        { text: 'حسابرس', level: 'medium', description: 'فردی که صحت حساب‌های مالی را بررسی می‌کند.' },
        { text: 'مدیر', level: 'medium', description: 'فردی که مسئول اداره یک سازمان است.' },
        { text: 'منشی', level: 'medium', description: 'فردی که امور دفتری را انجام می‌دهد.' },
        { text: 'دفتردار', level: 'medium', description: 'فردی که اسناد و مدارک را نگهداری می‌کند.' },
        { text: 'برقکار', level: 'medium', description: 'فردی که با سیستم‌های برقی کار می‌کند.' },
        { text: 'لوله کش', level: 'medium', description: 'فردی که لوله‌کشی آب و فاضلاب را انجام می‌دهد.' },
        { text: 'جوشکار', level: 'medium', description: 'فردی که با جوش دادن فلزات کار می‌کند.' },
        { text: 'بازاریاب', level: 'medium', description: 'فردی که محصولات را تبلیغ و می‌فروشد.' },
        { text: 'تحلیلگر', level: 'medium', description: 'فردی که داده‌ها و اطلاعات را بررسی می‌کند.' },
        { text: 'استاد', level: 'medium', description: 'معلم در سطح دانشگاهی.' },
        { text: 'کشاورز', level: 'medium', description: 'فردی که به کشت و زرع می‌پردازد.' },
        { text: 'دامدار', level: 'medium', description: 'فردی که از حیوانات اهلی نگهداری می‌کند.' },
        { text: 'پژوهشگر', level: 'medium', description: 'فردی که به تحقیق و مطالعه می‌پردازد.' },
        { text: 'استراتژیست', level: 'medium', description: 'فردی که طرح‌های بلندمدت می‌ریزد.' },
        { text: 'متصدی', level: 'medium', description: 'فردی که مسئول یک دستگاه یا کار خاص است.' },
        { text: 'بایگان', level: 'medium', description: 'فردی که وظیفه نگهداری و مرتب‌سازی مدارک را دارد.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'مهندس نرم افزار', level: 'hard', description: 'فردی که به طراحی و ساخت نرم‌افزارهای کامپیوتری می‌پردازد.' },
        { text: 'متخصص امنیت', level: 'hard', description: 'فردی که وظیفه حفاظت از اطلاعات در برابر تهدیدات سایبری را دارد.' },
        { text: 'مدیر عامل', level: 'hard', description: 'بالاترین مقام اجرایی در یک شرکت.' },
        { text: 'کارشناس منابع انسانی', level: 'hard', description: 'فردی که امور مربوط به کارکنان را مدیریت می‌کند.' },
        { text: 'توسعه دهنده وب', level: 'hard', description: 'فردی که وب‌سایت‌ها و اپلیکیشن‌های تحت وب را می‌سازد.' },
        { text: 'آبدارچی', level: 'hard', description: 'فردی که مسئول تهیه چای و پذیرایی در یک اداره است.' },
        { text: 'تکنیسین', level: 'hard', description: 'فردی که در یک حوزه فنی متخصص است.' },
        { text: 'صنعتگر دستی', level: 'hard', description: 'فردی که با دست، صنایع دستی می‌سازد.' },
        { text: 'مشاور املاک', level: 'hard', description: 'فردی که در خرید و فروش ملک کمک می‌کند.' },
        { text: 'پرستار', level: 'hard', description: 'فردی که از بیماران مراقبت می‌کند.' },
        { text: 'مامور پذیرش', level: 'hard', description: 'فردی که در ورودی سازمان، ارباب رجوع را راهنمایی می‌کند.' },
        { text: 'موزه‌دار', level: 'hard', description: 'فردی که مسئول نگهداری و نمایش آثار در موزه است.' },
        { text: 'سردبیر', level: 'hard', description: 'فردی که مسئول نهایی محتوای یک نشریه است.' },
        { text: 'طراح لباس', level: 'hard', description: 'فردی که مدل‌های جدید لباس را طراحی می‌کند.' },
        { text: 'آهنگساز', level: 'hard', description: 'فردی که موسیقی خلق می‌کند.' },
        { text: 'تنظیم کننده', level: 'hard', description: 'فردی که موسیقی را برای سازهای مختلف تنظیم می‌کند.' },
        { text: 'گرافیست', level: 'hard', description: 'فردی که طرح‌های بصری را طراحی می‌کند.' },
        { text: 'بازرس', level: 'hard', description: 'فردی که برای بررسی و نظارت فرستاده می‌شود.' },
        { text: 'صراف', level: 'hard', description: 'فردی که به خرید و فروش ارز می‌پردازد.' },
        { text: 'مدل ساز', level: 'hard', description: 'فردی که ماکت یا نمونه‌های اولیه می‌سازد.' },
        { text: 'زمین شناس', level: 'hard', description: 'فردی که به مطالعه ساختار و تاریخ زمین می‌پردازد.' },
        { text: 'ستاره شناس', level: 'hard', description: 'فردی که به مطالعه اجرام آسمانی می‌پردازد.' },
        { text: 'محیط بان', level: 'hard', description: 'فردی که از محیط زیست و حیات وحش مراقبت می‌کند.' },
        { text: 'افسر ارشد', level: 'hard', description: 'فردی با رتبه بالا در ارتش یا نیروی انتظامی.' },
        { text: 'پرتاب کننده موشک', level: 'hard', description: 'شغلی در حوزه نظامی یا فضایی.' },
        { text: 'مدیریت پروژه', level: 'hard', description: 'فردی که مسئول برنامه‌ریزی و اجرای یک پروژه است.' },
        { text: 'مستند ساز', level: 'hard', description: 'فردی که به ساخت فیلم‌های مستند می‌پردازد.' },
        { text: 'تحلیلگر بازار', level: 'hard', description: 'فردی که روندها و داده‌های اقتصادی را بررسی می‌کند.' },
        { text: 'متخصص فروش', level: 'hard', description: 'فردی با تخصص بالا در فروش محصولات.' },
        { text: 'متصدی امور مالی', level: 'hard', description: 'فردی که امور مربوط به سرمایه و بودجه را انجام می‌دهد.' },
        { text: 'مسئول تدارکات', level: 'hard', description: 'فردی که مسئول تهیه لوازم و تجهیزات است.' },
        { text: 'طراح داخلی', level: 'hard', description: 'فردی که فضاهای داخلی ساختمان‌ها را طراحی می‌کند.' },
        { text: 'برگزار کننده مراسم', level: 'hard', description: 'فردی که وظیفه برنامه‌ریزی رویدادها را بر عهده دارد.' },
        { text: 'معلم خصوصی', level: 'hard', description: 'فردی که به صورت فردی به دانش‌آموز آموزش می‌دهد.' },
      ],
    },
    // ====================================================================================================================
    // === ۹. کشورهای جهان (۱۰۰ کلمه) - دسته‌بندی جدید ===
    // ====================================================================================================================
    {
      name: 'کشورهای جهان',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'ایران', level: 'easy', description: 'کشوری در خاورمیانه با پایتخت تهران.' },
        { text: 'چین', level: 'easy', description: 'پرجمعیت‌ترین کشور جهان.' },
        { text: 'هند', level: 'easy', description: 'کشور بزرگ در جنوب آسیا.' },
        { text: 'ترکیه', level: 'easy', description: 'کشوری با مرزهای آسیا و اروپا.' },
        { text: 'عراق', level: 'easy', description: 'کشور همسایه غربی ایران.' },
        { text: 'عمان', level: 'easy', description: 'کشور عربی در خلیج فارس.' },
        { text: 'یمن', level: 'easy', description: 'کشور عربی در جنوب شبه جزیره عربستان.' },
        { text: 'قطر', level: 'easy', description: 'شبه جزیره‌ای کوچک در خلیج فارس.' },
        { text: 'کره', level: 'easy', description: 'منطقه‌ای که به دو کشور شمالی و جنوبی تقسیم شده.' },
        { text: 'روسیه', level: 'easy', description: 'بزرگترین کشور جهان از نظر مساحت.' },
        { text: 'سوئد', level: 'easy', description: 'کشوری در شمال اروپا.' },
        { text: 'نروژ', level: 'easy', description: 'کشوری در اسکاندیناوی.' },
        { text: 'آلمان', level: 'easy', description: 'کشور صنعتی در اروپای مرکزی.' },
        { text: 'لهستان', level: 'easy', description: 'کشوری در اروپای شرقی.' },
        { text: 'ایتالیا', level: 'easy', description: 'کشوری در جنوب اروپا با شکل چکمه.' },
        { text: 'یونان', level: 'easy', description: 'کشوری باستانی در جنوب اروپا.' },
        { text: 'شیلی', level: 'easy', description: 'کشور باریک و دراز در آمریکای جنوبی.' },
        { text: 'کوبا', level: 'easy', description: 'جزیره‌ای در دریای کارائیب.' },
        { text: 'ژاپن', level: 'easy', description: 'کشور جزیره‌ای در شرق آسیا.' },
        { text: 'مصر', level: 'easy', description: 'کشور عربی با اهرام ثلاثه.' },
        { text: 'کنگو', level: 'easy', description: 'کشوری در آفریقای مرکزی.' },
        { text: 'غنا', level: 'easy', description: 'کشوری در غرب آفریقا.' },
        { text: 'بنگلادش', level: 'easy', description: 'کشوری پرجمعیت در جنوب آسیا.' },
        { text: 'نپال', level: 'easy', description: 'کشوری در کوه‌های هیمالیا.' },
        { text: 'بوتان', level: 'easy', description: 'کشور کوچک در شرق هیمالیا.' },
        { text: 'آرژانتین', level: 'easy', description: 'کشور بزرگ در آمریکای جنوبی.' },
        { text: 'برزیل', level: 'easy', description: 'بزرگترین کشور آمریکای جنوبی.' },
        { text: 'پرو', level: 'easy', description: 'کشوری باستانی در آمریکای جنوبی.' },
        { text: 'مکزیک', level: 'easy', description: 'کشوری در آمریکای شمالی با فرهنگ غنی.' },
        { text: 'کانادا', level: 'easy', description: 'دومین کشور بزرگ جهان از نظر مساحت.' },
        { text: 'آمریکا', level: 'easy', description: 'کشور قدرتمند در آمریکای شمالی.' },
        { text: 'فرانسه', level: 'easy', description: 'کشوری در اروپای غربی با پایتخت پاریس.' },
        { text: 'انگلستان', level: 'easy', description: 'کشور جزیره‌ای در غرب اروپا.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'افغانستان', level: 'medium', description: 'کشور همسایه شرقی ایران.' },
        { text: 'پاکستان', level: 'medium', description: 'کشور همسایه شرقی ایران در جنوب آسیا.' },
        { text: 'عربستان', level: 'medium', description: 'بزرگترین کشور شبه جزیره عربستان.' },
        { text: 'آذربایجان', level: 'medium', description: 'کشور همسایه شمال غربی ایران.' },
        { text: 'قزاقستان', level: 'medium', description: 'کشور بزرگ آسیای مرکزی.' },
        { text: 'ازبکستان', level: 'medium', description: 'کشوری در آسیای مرکزی با شهرهای تاریخی.' },
        { text: 'ترکمنستان', level: 'medium', description: 'کشور همسایه شمال شرقی ایران.' },
        { text: 'امارات', level: 'medium', description: 'کشور عربی با شهر دبی.' },
        { text: 'بحرین', level: 'medium', description: 'کشور جزیره‌ای کوچک در خلیج فارس.' },
        { text: 'کویت', level: 'medium', description: 'کشور عربی در خلیج فارس با ذخایر نفتی.' },
        { text: 'فلسطین', level: 'medium', description: 'منطقه‌ای در خاورمیانه.' },
        { text: 'اردن', level: 'medium', description: 'کشور عربی با جاذبه‌های تاریخی.' },
        { text: 'لبنان', level: 'medium', description: 'کشور کوچک در خاورمیانه با پایتخت بیروت.' },
        { text: 'سوریه', level: 'medium', description: 'کشور در خاورمیانه.' },
        { text: 'یونان', level: 'medium', description: 'کشور باستانی در جنوب اروپا.' },
        { text: 'اسپانیا', level: 'medium', description: 'کشوری در جنوب غرب اروپا.' },
        { text: 'پرتغال', level: 'medium', description: 'کشوری در غرب شبه جزیره ایبری.' },
        { text: 'هلند', level: 'medium', description: 'کشور اروپایی معروف به آسیاب‌های بادی.' },
        { text: 'بلژیک', level: 'medium', description: 'کشور کوچک اروپایی.' },
        { text: 'سوئیس', level: 'medium', description: 'کشور کوهستانی و بی‌طرف در اروپا.' },
        { text: 'اتریش', level: 'medium', description: 'کشوری در اروپای مرکزی.' },
        { text: 'کرواسی', level: 'medium', description: 'کشوری در جنوب شرق اروپا.' },
        { text: 'صربستان', level: 'medium', description: 'کشوری در بالکان.' },
        { text: 'رومانی', level: 'medium', description: 'کشوری در اروپای شرقی.' },
        { text: 'اوکراین', level: 'medium', description: 'کشور بزرگ در اروپای شرقی.' },
        { text: 'ونزوئلا', level: 'medium', description: 'کشور با ذخایر نفتی در آمریکای جنوبی.' },
        { text: 'کلمبیا', level: 'medium', description: 'کشوری در شمال غرب آمریکای جنوبی.' },
        { text: 'شیلی', level: 'medium', description: 'کشور باریک و دراز در آمریکای جنوبی.' },
        { text: 'الجزایر', level: 'medium', description: 'بزرگترین کشور آفریقا.' },
        { text: 'مراکش', level: 'medium', description: 'کشوری در شمال آفریقا.' },
        { text: 'سودان', level: 'medium', description: 'کشور آفریقایی با پایتخت خارطوم.' },
        { text: 'تایلند', level: 'medium', description: 'کشوری در جنوب شرق آسیا.' },
        { text: 'ویتنام', level: 'medium', description: 'کشوری در جنوب شرق آسیا.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'جمهوری اسلامی ایران', level: 'hard', description: 'نام رسمی کشور ایران.' },
        { text: 'پادشاهی عربستان سعودی', level: 'hard', description: 'نام رسمی کشور عربستان.' },
        { text: 'ایالات متحده آمریکا', level: 'hard', description: 'نام رسمی کشور آمریکا.' },
        { text: 'جمهوری خلق چین', level: 'hard', description: 'نام رسمی کشور چین.' },
        { text: 'جمهوری ترکیه', level: 'hard', description: 'نام رسمی کشور ترکیه.' },
        { text: 'بریتانیای کبیر', level: 'hard', description: 'نام جزیره بزرگ انگلیس.' },
        { text: 'جمهوری فرانسه', level: 'hard', description: 'نام رسمی کشور فرانسه.' },
        { text: 'جمهوری ایتالیا', level: 'hard', description: 'نام رسمی کشور ایتالیا.' },
        { text: 'جمهوری خلق بنگلادش', level: 'hard', description: 'نام رسمی کشور بنگلادش.' },
        { text: 'افریقای جنوبی', level: 'hard', description: 'کشوری در جنوبی‌ترین نقطه قاره آفریقا.' },
        { text: 'نیوزلند', level: 'hard', description: 'کشور جزیره‌ای در جنوب غرب اقیانوس آرام.' },
        { text: 'استرالیا', level: 'hard', description: 'قاره‌ای که یک کشور است.' },
        { text: 'کره جنوبی', level: 'hard', description: 'کشوری در شرق آسیا، پایتخت سئول.' },
        { text: 'کره شمالی', level: 'hard', description: 'کشوری در شرق آسیا با حکومتی بسته.' },
        { text: 'اندونزی', level: 'hard', description: 'بزرگترین کشور جزیره‌ای جهان.' },
        { text: 'مالزی', level: 'hard', description: 'کشوری در جنوب شرق آسیا با پایتخت کوالالامپور.' },
        { text: 'فیلیپین', level: 'hard', description: 'کشور جزیره‌ای در اقیانوس آرام.' },
        { text: 'دانمارک', level: 'hard', description: 'کشوری در شمال اروپا، بخشی از اسکاندیناوی.' },
        { text: 'فنلاند', level: 'hard', description: 'کشوری در شمال اروپا معروف به سرزمین هزار دریاچه.' },
        { text: 'ایسلند', level: 'hard', description: 'جزیره‌ای در شمال اقیانوس اطلس.' },
        { text: 'آرژانتین', level: 'hard', description: 'کشور بزرگ در آمریکای جنوبی.' },
        { text: 'بولیوی', level: 'hard', description: 'کشور محصور در خشکی در آمریکای جنوبی.' },
        { text: 'اکوادور', level: 'hard', description: 'کشوری در آمریکای جنوبی با خط استوا.' },
        { text: 'پاراگوئه', level: 'hard', description: 'کشور محصور در خشکی در آمریکای جنوبی.' },
        { text: 'اروگوئه', level: 'hard', description: 'کشور کوچک در آمریکای جنوبی.' },
        { text: 'جامائیکا', level: 'hard', description: 'جزیره‌ای در دریای کارائیب.' },
        { text: 'برمه (میانمار)', level: 'hard', description: 'کشوری در جنوب شرق آسیا.' },
        { text: 'سنگاپور', level: 'hard', description: 'کشور-شهر در جنوب شرق آسیا.' },
        { text: 'نیجریه', level: 'hard', description: 'پرجمعیت‌ترین کشور آفریقا.' },
        { text: 'اتیوپی', level: 'hard', description: 'کشور در شرق آفریقا.' },
        { text: 'کامرون', level: 'hard', description: 'کشوری در غرب آفریقا.' },
        { text: 'زیمبابوه', level: 'hard', description: 'کشوری در جنوب آفریقا.' },
        { text: 'ماکائو', level: 'hard', description: 'منطقه ویژه اداری در چین، معروف به قمار.' },
        { text: 'فدرال', level: 'hard', description: 'نوعی سیستم حکومتی.' },
      ],
    },
    // ====================================================================================================================
    // === ۱۰. مفاهیم انتزاعی و انتشارات (۱۰۰ کلمه) - دسته‌بندی جدید ===
    // ====================================================================================================================
    {
      name: 'مفاهیم انتزاعی و انتشارات',
      words: [
        // --- Easy (۳ تا ۵ حرفی) - ۳۳ کلمه ---
        { text: 'عشق', level: 'easy', description: 'احساس عمیق و شدید علاقه.' },
        { text: 'امید', level: 'easy', description: 'انتظار مثبت برای آینده.' },
        { text: 'شادی', level: 'easy', description: 'حالت درونی خوشحالی.' },
        { text: 'غم', level: 'easy', description: 'احساس ناراحتی عمیق.' },
        { text: 'ترس', level: 'easy', description: 'احساس ناخوشایند ناشی از خطر.' },
        { text: 'خواب', level: 'easy', description: 'حالت استراحت ذهن و بدن.' },
        { text: 'زمان', level: 'easy', description: 'مفهوم اندازه‌گیری توالی وقایع.' },
        { text: 'فکر', level: 'easy', description: 'عملیات ذهنی.' },
        { text: 'خرد', level: 'easy', description: 'دانش و تجربه عمیق.' },
        { text: 'ذهن', level: 'easy', description: 'محل تفکر و آگاهی.' },
        { text: 'جان', level: 'easy', description: 'روح یا نیروی حیات.' },
        { text: 'هوا', level: 'easy', description: 'فضای اطراف زمین.' },
        { text: 'صبر', level: 'easy', description: 'توانایی تحمل تأخیر یا رنج.' },
        { text: 'نظم', level: 'easy', description: 'ترتیب و سازماندهی.' },
        { text: 'راز', level: 'easy', description: 'موضوعی پنهان.' },
        { text: 'هنر', level: 'easy', description: 'خلق آثار زیبا.' },
        { text: 'علم', level: 'easy', description: 'دانش مبتنی بر تحقیق.' },
        { text: 'دین', level: 'easy', description: 'سیستم اعتقادی و پرستش.' },
        { text: 'فلسفه', level: 'easy', description: 'مطالعه ماهیت واقعیت و دانش.' },
        { text: 'منطق', level: 'easy', description: 'علم استدلال صحیح.' },
        { text: 'پول', level: 'easy', description: 'واسطه مبادله اقتصادی.' },
        { text: 'بورس', level: 'easy', description: 'بازار خرید و فروش سهام.' },
        { text: 'سود', level: 'easy', description: 'منفعت مالی.' },
        { text: 'ضرر', level: 'easy', description: 'زیان مالی.' },
        { text: 'ثروت', level: 'easy', description: 'مقدار زیادی پول یا دارایی.' },
        { text: 'فقر', level: 'easy', description: 'کمبود شدید امکانات مالی.' },
        { text: 'جنگ', level: 'easy', description: 'درگیری مسلحانه بین کشورها.' },
        { text: 'صلح', level: 'easy', description: 'نبود جنگ و درگیری.' },
        { text: 'انرژی', level: 'easy', description: 'ظرفیت انجام کار.' },
        { text: 'قانون', level: 'easy', description: 'مجموعه‌ای از قواعد رسمی.' },
        { text: 'سیاست', level: 'easy', description: 'فعالیت‌های حکومتی.' },
        { text: 'عدالت', level: 'easy', description: 'برخورد عادلانه و منصفانه.' },
        { text: 'خشم', level: 'easy', description: 'احساس شدید ناخوشایندی.' },
        // --- Medium (۶ تا ۸ حرفی) - ۳۳ کلمه ---
        { text: 'آزادی', level: 'medium', description: 'حالت رهایی از محدودیت.' },
        { text: 'وفاداری', level: 'medium', description: 'پایبندی به شخص یا آرمان.' },
        { text: 'احترام', level: 'medium', description: 'ارزش قائل شدن برای دیگران.' },
        { text: 'قدرت', level: 'medium', description: 'توانایی کنترل یا تأثیرگذاری.' },
        { text: 'حافظه', level: 'medium', description: 'توانایی ذهن برای ذخیره اطلاعات.' },
        { text: 'خیال', level: 'medium', description: 'تصورات یا رویاهای ذهنی.' },
        { text: 'شخصیت', level: 'medium', description: 'ویژگی‌های فردی.' },
        { text: 'وجدان', level: 'medium', description: 'حس اخلاقی درونی.' },
        { text: 'تعهد', level: 'medium', description: 'التزام به انجام کاری.' },
        { text: 'اعتبار', level: 'medium', description: 'شایستگی یا شأن.' },
        { text: 'فرضیه', level: 'medium', description: 'حدس علمی اولیه.' },
        { text: 'تئوری', level: 'medium', description: 'مجموعه‌ای از اصول علمی.' },
        { text: 'اخلاق', level: 'medium', description: 'مجموعه‌ای از اصول رفتاری.' },
        { text: 'دشمنی', level: 'medium', description: 'حالت خصومت و کینه.' },
        { text: 'دوستی', level: 'medium', description: 'رابطه محبت‌آمیز بین افراد.' },
        { text: 'تلاش', level: 'medium', description: 'کوشش و کوشش.' },
        { text: 'موفقیت', level: 'medium', description: 'دستیابی به هدف.' },
        { text: 'شکست', level: 'medium', description: 'عدم دستیابی به هدف.' },
        { text: 'ثبات', level: 'medium', description: 'حالت پایداری و تغییر ناپذیری.' },
        { text: 'فرهنگ', level: 'medium', description: 'آداب، رسوم و ارزش‌های یک گروه.' },
        { text: 'تاریخ', level: 'medium', description: 'مطالعه گذشته.' },
        { text: 'ادبیات', level: 'medium', description: 'نوشته‌های هنری.' },
        { text: 'اقتصاد', level: 'medium', description: 'علم مدیریت منابع.' },
        { text: 'آموزش', level: 'medium', description: 'فرآیند یادگیری دانش و مهارت.' },
        { text: 'تربیت', level: 'medium', description: 'پرورش اخلاقی و رفتاری.' },
        { text: 'تجارت', level: 'medium', description: 'فعالیت خرید و فروش.' },
        { text: 'سرمایه', level: 'medium', description: 'منابع مالی یا دارایی.' },
        { text: 'بدهی', level: 'medium', description: 'مقدار پولی که باید پس داده شود.' },
        { text: 'مالیات', level: 'medium', description: 'وجهی که به دولت پرداخت می‌شود.' },
        { text: 'ارزش', level: 'medium', description: 'اهمیت یک چیز.' },
        { text: 'تصور', level: 'medium', description: 'شکل دادن به یک تصویر ذهنی.' },
        { text: 'انتخاب', level: 'medium', description: 'فرآیند تصمیم‌گیری.' },
        { text: 'هدف', level: 'medium', description: 'نقطه نهایی یا نتیجه مورد نظر.' },
        // --- Hard (۹ حرفی یا بیشتر / چند کلمه‌ای) - ۳۴ کلمه ---
        { text: 'خودآگاهی', level: 'hard', description: 'آگاهی از خود، شخصیت و انگیزه‌ها.' },
        { text: 'استدلال منطقی', level: 'hard', description: 'فکر کردن به شیوه‌ای منظم و صحیح.' },
        { text: 'بحران هویت', level: 'hard', description: 'دوره عدم اطمینان در مورد نقش و جایگاه خود.' },
        { text: 'مفهوم انتزاعی', level: 'hard', description: 'ایده‌ای که وجود فیزیکی ندارد.' },
        { text: 'فرایند شناختی', level: 'hard', description: 'عملیات ذهنی مربوط به کسب دانش.' },
        { text: 'روانکاوی', level: 'hard', description: 'روش درمانی مبتنی بر کاوش ذهن ناخودآگاه.' },
        { text: 'معنای زندگی', level: 'hard', description: 'مفهوم هدف و ارزش وجود انسان.' },
        { text: 'اقتصاد کلان', level: 'hard', description: 'مطالعه عملکرد اقتصاد به صورت کلی.' },
        { text: 'اقتصاد خرد', level: 'hard', description: 'مطالعه رفتار افراد و شرکت‌ها در تصمیم‌گیری.' },
        { text: 'توسعه پایدار', level: 'hard', description: 'توسعه‌ای که نیازهای نسل فعلی را بدون به خطر انداختن نسل‌های آینده برآورده کند.' },
        { text: 'حقوق بشر', level: 'hard', description: 'حقوق اساسی که هر فرد به دلیل انسان بودن دارد.' },
        { text: 'انقلاب صنعتی', level: 'hard', description: 'دوره تحول بزرگ در تولید کالا.' },
        { text: 'انقلاب فرانسه', level: 'hard', description: 'دوره تحول سیاسی و اجتماعی در فرانسه.' },
        { text: 'دموکراسی', level: 'hard', description: 'سیستم حکومتی که مردم در آن رأی می‌دهند.' },
        { text: 'توتالیتاریسم', level: 'hard', description: 'سیستم حکومتی با کنترل کامل بر زندگی عمومی و خصوصی.' },
        { text: 'جهانی شدن', level: 'hard', description: 'افزایش وابستگی و تعامل بین کشورها.' },
        { text: 'جامعه شناسی', level: 'hard', description: 'علم مطالعه جامعه و روابط اجتماعی.' },
        { text: 'انسان شناسی', level: 'hard', description: 'مطالعه انسان‌ها، رفتار و جوامع آن‌ها.' },
        { text: 'فناوری اطلاعات', level: 'hard', description: 'استفاده از رایانه‌ها و نرم‌افزار برای مدیریت اطلاعات.' },
        { text: 'مدیریت استراتژیک', level: 'hard', description: 'مدیریت برای دستیابی به اهداف بلندمدت.' },
        { text: 'فرهنگ عامه', level: 'hard', description: 'عقاید، آداب و رسوم رایج در یک جامعه.' },
        { text: 'پست مدرنیسم', level: 'hard', description: 'جنبشی فکری که باورهای سنتی را زیر سؤال می‌برد.' },
        { text: 'محیط زیست', level: 'hard', description: 'طبیعت و شرایطی که موجودات زنده در آن زندگی می‌کنند.' },
        { text: 'آلودگی هوا', level: 'hard', description: 'وجود مواد مضر در جو.' },
        { text: 'سرمایه گذاری', level: 'hard', description: 'تخصیص پول با انتظار کسب سود در آینده.' },
        { text: 'ناخودآگاه', level: 'hard', description: 'بخشی از ذهن که فراتر از آگاهی است.' },
        { text: 'تفکر انتقادی', level: 'hard', description: 'تجزیه و تحلیل واقعیت‌ها برای تشکیل قضاوت.' },
        { text: 'نشر الکترونیک', level: 'hard', description: 'انتشار محتوا در قالب دیجیتال.' },
        { text: 'روزنامه کثیرالانتشار', level: 'hard', description: 'روزنامه‌ای با تیراژ بالا.' },
        { text: 'مطبوعات', level: 'hard', description: 'نشریات و رسانه‌های چاپی.' },
        { text: 'خبرگزاری رسمی', level: 'hard', description: 'سازمانی که اخبار دولتی را منتشر می‌کند.' },
        { text: 'نظریه تکامل', level: 'hard', description: 'تغییر ویژگی‌های وراثتی جمعیت‌های زیستی در طول نسل‌ها.' },
        { text: 'اخلاق حرفه ای', level: 'hard', description: 'اصول اخلاقی حاکم بر یک حرفه.' },
        { text: 'ارتباطات جمعی', level: 'hard', description: 'انتقال پیام از طریق رسانه‌های گسترده.' },
      ],
    },
  ],
};
