// words.js — بخش ۱ از ۵ (۲۰۰ کلمه)
// همهٔ کلمات رایج، بدون نیم‌فاصله (space فقط)، سطح‌بندی و دسته‌بندی شده

module.exports = {
  categories: [
    // حیوانات (20)
    {
      name: 'حیوانات',
      words: [
        { text: 'گربه', level: 'easy' },
        { text: 'سگ', level: 'easy' },
        { text: 'اسب', level: 'easy' },
        { text: 'گنجشک', level: 'easy' },
        { text: 'کلاغ', level: 'easy' },
        { text: 'خرگوش', level: 'easy' },
        { text: 'شیر', level: 'easy' },
        { text: 'ببر', level: 'easy' },
        { text: 'پلنگ', level: 'medium' },
        { text: 'فیل', level: 'easy' },
        { text: 'زرافه', level: 'easy' },
        { text: 'روباه', level: 'easy' },
        { text: 'گرگ', level: 'easy' },
        { text: 'خرس قهوه ای', level: 'medium' },
        { text: 'خرس قطبی', level: 'medium' },
        { text: 'پنگوئن', level: 'medium' },
        { text: 'لاک پشت', level: 'medium' },
        { text: 'کرگدن', level: 'medium' },
        { text: 'یوزپلنگ', level: 'medium' },
        { text: 'دلفین', level: 'easy' },
      ],
    },

    // میوه‌ها (20)
    {
      name: 'میوه ها',
      words: [
        { text: 'سیب', level: 'easy' },
        { text: 'پرتقال', level: 'easy' },
        { text: 'گلابی', level: 'easy' },
        { text: 'هندوانه', level: 'easy' },
        { text: 'طالبی', level: 'easy' },
        { text: 'ملون', level: 'easy' },
        { text: 'انار', level: 'easy' },
        { text: 'انگور', level: 'easy' },
        { text: 'زرد آلو', level: 'easy' },
        { text: 'هلو', level: 'easy' },
        { text: 'آلو', level: 'easy' },
        { text: 'گیلاس', level: 'easy' },
        { text: 'آلبالو', level: 'easy' },
        { text: 'کیوی', level: 'easy' },
        { text: 'موز', level: 'easy' },
        { text: 'انبه', level: 'easy' },
        { text: 'نارگیل', level: 'medium' },
        { text: 'لیمو ترش', level: 'easy' },
        { text: 'گریپ فروت', level: 'medium' },
        { text: 'خرمالو', level: 'medium' },
      ],
    },

    // شهرها (20)
    {
      name: 'شهرها',
      words: [
        { text: 'تهران', level: 'easy' },
        { text: 'مشهد', level: 'easy' },
        { text: 'اصفهان', level: 'easy' },
        { text: 'تبریز', level: 'easy' },
        { text: 'شیراز', level: 'easy' },
        { text: 'کرمان', level: 'easy' },
        { text: 'اهواز', level: 'easy' },
        { text: 'یزد', level: 'easy' },
        { text: 'رشت', level: 'easy' },
        { text: 'قزوین', level: 'easy' },
        { text: 'اردبیل', level: 'easy' },
        { text: 'زنجان', level: 'easy' },
        { text: 'گرگان', level: 'easy' },
        { text: 'بندرعباس', level: 'medium' },
        { text: 'بوشهر', level: 'easy' },
        { text: 'کیش', level: 'easy' },
        { text: 'قم', level: 'easy' },
        { text: 'همدان', level: 'easy' },
        { text: 'سمنان', level: 'easy' },
        { text: 'سنندج', level: 'medium' },
      ],
    },

    // رنگ‌ها (20)
    {
      name: 'رنگ ها',
      words: [
        { text: 'قرمز', level: 'easy' },
        { text: 'آبی', level: 'easy' },
        { text: 'سبز', level: 'easy' },
        { text: 'زرد', level: 'easy' },
        { text: 'نارنجی', level: 'easy' },
        { text: 'صورتی', level: 'easy' },
        { text: 'بنفش', level: 'easy' },
        { text: 'قهوه ای', level: 'easy' },
        { text: 'خاکستری', level: 'easy' },
        { text: 'مشکی', level: 'easy' },
        { text: 'سفید', level: 'easy' },
        { text: 'سرمه ای', level: 'easy' },
        { text: 'لاجوردی', level: 'medium' },
        { text: 'یاسی', level: 'easy' },
        { text: 'زرشکی', level: 'easy' },
        { text: 'گلبهی', level: 'easy' },
        { text: 'طلایی', level: 'medium' },
        { text: 'نقره ای', level: 'easy' },
        { text: 'فیروزه ای', level: 'medium' },
        { text: 'کندویی', level: 'medium' },
      ],
    },

    // اشیا (20)
    {
      name: 'اشیا',
      words: [
        { text: 'میز', level: 'easy' },
        { text: 'صندلی', level: 'easy' },
        { text: 'کمد', level: 'easy' },
        { text: 'کتابخانه', level: 'medium' },
        { text: 'یخچال', level: 'medium' },
        { text: 'تلویزیون', level: 'easy' },
        { text: 'ماشین لباس شویی', level: 'medium' },
        { text: 'گوشی همراه', level: 'easy' },
        { text: 'لپ تاپ', level: 'easy' },
        { text: 'ساعت دیواری', level: 'easy' },
        { text: 'تابلو نقاشی', level: 'medium' },
        { text: 'قاب عکس', level: 'easy' },
        { text: 'لامپ کم مصرف', level: 'easy' },
        { text: 'دوربین عکاسی', level: 'medium' },
        { text: 'موکت', level: 'easy' },
        { text: 'فرش دست بافت', level: 'hard' },
        { text: 'چرخ خیاطی', level: 'medium' },
        { text: 'کنترل تلویزیون', level: 'easy' },
        { text: 'پریز برق', level: 'easy' },
        { text: 'کلید چراغ', level: 'easy' },
      ],
    },

    // خوراکی‌ها (20)
    {
      name: 'خوراکی ها',
      words: [
        { text: 'نان بربری', level: 'easy' },
        { text: 'نان سنگک', level: 'easy' },
        { text: 'نان تافتون', level: 'easy' },
        { text: 'پنیر لیقوان', level: 'medium' },
        { text: 'ماست چکیده', level: 'easy' },
        { text: 'کره', level: 'easy' },
        { text: 'تخم مرغ', level: 'easy' },
        { text: 'عدس پلو', level: 'easy' },
        { text: 'لوبیا پلو', level: 'easy' },
        { text: 'قیمه', level: 'easy' },
        { text: 'قرمه سبزی', level: 'easy' },
        { text: 'زرشک پلو', level: 'easy' },
        { text: 'کباب کوبیده', level: 'easy' },
        { text: 'جوجه کباب', level: 'easy' },
        { text: 'کله پاچه', level: 'medium' },
        { text: 'دیزی سنگی', level: 'medium' },
        { text: 'آش رشته', level: 'easy' },
        { text: 'سوپ جو', level: 'easy' },
        { text: 'شله زرد', level: 'easy' },
        { text: 'فالوده شیرازی', level: 'medium' },
      ],
    },

    // ورزش‌ها (20)
    {
      name: 'ورزش ها',
      words: [
        { text: 'فوتبال', level: 'easy' },
        { text: 'بسکتبال', level: 'easy' },
        { text: 'والیبال', level: 'easy' },
        { text: 'هندبال', level: 'easy' },
        { text: 'تنیس', level: 'easy' },
        { text: 'تکواندو', level: 'medium' },
        { text: 'کاراته', level: 'easy' },
        { text: 'جودو', level: 'easy' },
        { text: 'شنا آزاد', level: 'easy' },
        { text: 'شنای پروانه', level: 'medium' },
        { text: 'دو میدانی', level: 'easy' },
        { text: 'شمشیربازی', level: 'medium' },
        { text: 'کشتی آزاد', level: 'easy' },
        { text: 'کشتی فرنگی', level: 'easy' },
        { text: 'بوکس', level: 'easy' },
        { text: 'تیراندازی', level: 'easy' },
        { text: 'اسکی آلپاین', level: 'medium' },
        { text: 'دوچرخه سواری', level: 'easy' },
        { text: 'ژیمناستیک هنری', level: 'medium' },
        { text: 'گلف', level: 'easy' },
      ],
    },

    // حرفه‌ها (20)
    {
      name: 'حرفه ها',
      words: [
        { text: 'پزشک', level: 'easy' },
        { text: 'پرستار', level: 'easy' },
        { text: 'معلم', level: 'easy' },
        { text: 'مهندس عمران', level: 'medium' },
        { text: 'مهندس نرم افزار', level: 'medium' },
        { text: 'طراح رابط کاربری', level: 'hard' },
        { text: 'آشپز', level: 'easy' },
        { text: 'نانوا', level: 'easy' },
        { text: 'بنا', level: 'easy' },
        { text: 'نجار', level: 'easy' },
        { text: 'برق کار', level: 'easy' },
        { text: 'لوله کش', level: 'easy' },
        { text: 'جوشکار', level: 'easy' },
        { text: 'نقاش ساختمان', level: 'easy' },
        { text: 'راننده تاکسی', level: 'easy' },
        { text: 'کارگردان سینما', level: 'hard' },
        { text: 'بازیگر تئاتر', level: 'medium' },
        { text: 'خبرنگار', level: 'easy' },
        { text: 'عکاس خبری', level: 'medium' },
        { text: 'پژوهشگر', level: 'medium' },
      ],
    },

    // طبیعت (20)
    {
      name: 'طبیعت',
      words: [
        { text: 'کوه بلند', level: 'easy' },
        { text: 'دشت پهناور', level: 'easy' },
        { text: 'بیابان گرم', level: 'easy' },
        { text: 'جنگل انبوه', level: 'easy' },
        { text: 'دریا آرام', level: 'easy' },
        { text: 'دریاچه نمک', level: 'medium' },
        { text: 'رودخانه خروشان', level: 'medium' },
        { text: 'چشمه زلال', level: 'easy' },
        { text: 'نیزار سبز', level: 'easy' },
        { text: 'تالاب فصلی', level: 'medium' },
        { text: 'غار آهکی', level: 'medium' },
        { text: 'صخره ساحلی', level: 'medium' },
        { text: 'برف سنگین', level: 'medium' },
        { text: 'باران شدید', level: 'easy' },
        { text: 'مه غلیظ', level: 'easy' },
        { text: 'نسیم خنک', level: 'easy' },
        { text: 'هوای پاک', level: 'easy' },
        { text: 'کرانه رود', level: 'easy' },
        { text: 'کوهپایه سرسبز', level: 'medium' },
        { text: 'دامنه کوه', level: 'easy' },
      ],
    },

    // فن آوری (20)
    {
      name: 'فن آوری',
      words: [
        { text: 'رایانه', level: 'easy' },
        { text: 'تلفن همراه', level: 'easy' },
        { text: 'اینترنت پر سرعت', level: 'easy' },
        { text: 'وای فای', level: 'easy' },
        { text: 'ابر داده', level: 'medium' },
        { text: 'رایانش ابری', level: 'medium' },
        { text: 'هوش مصنوعی', level: 'medium' },
        { text: 'یادگیری ماشین', level: 'hard' },
        { text: 'شبکه عصبی', level: 'hard' },
        { text: 'پردازنده مرکزی', level: 'medium' },
        { text: 'حافظه جانبی', level: 'easy' },
        { text: 'پایگاه داده', level: 'medium' },
        { text: 'زبان برنامه نویسی', level: 'medium' },
        { text: 'سامانه توزیع شده', level: 'hard' },
        { text: 'امنیت اطلاعات', level: 'medium' },
        { text: 'رمز نگاری', level: 'medium' },
        { text: 'رایانش گویا', level: 'hard' },
        { text: 'واقعیت افزوده', level: 'medium' },
        { text: 'واقعیت مجازی', level: 'medium' },
        { text: 'ربات صنعتی', level: 'medium' },
      ],
    },

    // هنر (10)
    {
      name: 'هنر',
      words: [
        { text: 'نقاشی رنگ روغن', level: 'medium' },
        { text: 'طراحی گرافیک', level: 'medium' },
        { text: 'خوش نویسی', level: 'medium' },
        { text: 'مجسمه سازی', level: 'medium' },
        { text: 'سفالگری', level: 'easy' },
        { text: 'قلم زنی', level: 'hard' },
        { text: 'مینیاتور ایرانی', level: 'hard' },
        { text: 'نگارگری سنتی', level: 'hard' },
        { text: 'عکاسی پرتره', level: 'medium' },
        { text: 'کولاژ هنری', level: 'medium' },
      ],
    },

    // موسیقی (10)
    {
      name: 'موسیقی',
      words: [
        { text: 'ساز تار', level: 'easy' },
        { text: 'ساز سه تار', level: 'easy' },
        { text: 'ساز سنتور', level: 'easy' },
        { text: 'ساز نی', level: 'easy' },
        { text: 'سه گاه', level: 'medium' },
        { text: 'چهار گاه', level: 'medium' },
        { text: 'ماهور', level: 'medium' },
        { text: 'شور', level: 'easy' },
        { text: 'نوا', level: 'medium' },
        { text: 'همایون', level: 'medium' },
      ],
    },

    // ادبیات (10)
    {
      name: 'ادبیات',
      words: [
        { text: 'غزل عاشقانه', level: 'easy' },
        { text: 'رباعی', level: 'easy' },
        { text: 'مثنوی', level: 'easy' },
        { text: 'قصیده', level: 'medium' },
        { text: 'پیکره شعر', level: 'hard' },
        { text: 'داستان کوتاه', level: 'easy' },
        { text: 'رمان تاریخی', level: 'medium' },
        { text: 'نمایش نامه', level: 'easy' },
        { text: 'نقد ادبی', level: 'medium' },
        { text: 'تصویر شاعرانه', level: 'hard' },
      ],
    },

    // ابزار (10)
    {
      name: 'ابزار',
      words: [
        { text: 'چکش آهنگری', level: 'medium' },
        { text: 'پیچ گوشتی چهار سو', level: 'medium' },
        { text: 'انبردست', level: 'easy' },
        { text: 'آچار فرانسه', level: 'easy' },
        { text: 'متر فلزی', level: 'easy' },
        { text: 'سوهان فلز', level: 'medium' },
        { text: 'اره دستی', level: 'easy' },
        { text: 'دریل شارژی', level: 'medium' },
        { text: 'تراز بنایی', level: 'easy' },
        { text: 'کارد میوه', level: 'easy' },
      ],
    },

    // علوم (10)
    {
      name: 'علوم',
      words: [
        { text: 'فیزیک کلاسیک', level: 'medium' },
        { text: 'شیمی آلی', level: 'medium' },
        { text: 'زیست شناسی', level: 'easy' },
        { text: 'زمین شناسی', level: 'easy' },
        { text: 'ریاضیات کاربردی', level: 'hard' },
        { text: 'آمار و احتمال', level: 'medium' },
        { text: 'هوا شناسی', level: 'medium' },
        { text: 'اختر شناسی', level: 'medium' },
        { text: 'مهندسی پزشکی', level: 'hard' },
        { text: 'ژنتیک مولکولی', level: 'hard' },
      ],
    },

    // احساسات (10)
    {
      name: 'احساسات',
      words: [
        { text: 'شادی', level: 'easy' },
        { text: 'غم', level: 'easy' },
        { text: 'ترس', level: 'easy' },
        { text: 'خشم', level: 'easy' },
        { text: 'هیجان', level: 'easy' },
        { text: 'دل شاد', level: 'easy' },
        { text: 'دل تنگ', level: 'easy' },
        { text: 'آرامش', level: 'easy' },
        { text: 'اضطراب', level: 'medium' },
        { text: 'دل نگرانی', level: 'easy' },
      ],
    },

    // صفات (10)
    {
      name: 'صفات',
      words: [
        { text: 'زیبا', level: 'easy' },
        { text: 'خوش رو', level: 'easy' },
        { text: 'مهربان', level: 'easy' },
        { text: 'صبور', level: 'easy' },
        { text: 'دقیق', level: 'easy' },
        { text: 'هوشمند', level: 'easy' },
        { text: 'خلاق', level: 'easy' },
        { text: 'جسور', level: 'easy' },
        { text: 'لجباز', level: 'medium' },
        { text: 'کمال جو', level: 'medium' },
      ],
    },

    // افعال (10)
    {
      name: 'افعال',
      words: [
        { text: 'نوشتن', level: 'easy' },
        { text: 'خواندن', level: 'easy' },
        { text: 'دویدن', level: 'easy' },
        { text: 'پختن', level: 'easy' },
        { text: 'خریدن', level: 'easy' },
        { text: 'فروختن', level: 'easy' },
        { text: 'آموختن', level: 'easy' },
        { text: 'آفریدن', level: 'medium' },
        { text: 'اندیشیدن', level: 'medium' },
        { text: 'نگاه کردن', level: 'easy' },
      ],
    },

    // بدن انسان (10)
    {
      name: 'بدن انسان',
      words: [
        { text: 'سر', level: 'easy' },
        { text: 'صورت', level: 'easy' },
        { text: 'چشم', level: 'easy' },
        { text: 'گوش', level: 'easy' },
        { text: 'بینی', level: 'easy' },
        { text: 'دهان', level: 'easy' },
        { text: 'گردن', level: 'easy' },
        { text: 'شانه', level: 'easy' },
        { text: 'بازو', level: 'easy' },
        { text: 'زانو', level: 'easy' },
      ],
    },

    // پوشاک (10)
    {
      name: 'پوشاک',
      words: [
        { text: 'پیراهن', level: 'easy' },
        { text: 'شلوار', level: 'easy' },
        { text: 'کت', level: 'easy' },
        { text: 'کفش', level: 'easy' },
        { text: 'جوراب', level: 'easy' },
        { text: 'کمربند', level: 'easy' },
        { text: 'کلاه زمستانی', level: 'easy' },
        { text: 'دستکش پشمی', level: 'easy' },
        { text: 'روسری نخی', level: 'easy' },
        { text: 'پالتو ضخیم', level: 'medium' },
      ],
    },
  ],
};
