// words.js
module.exports = [
    // Cities
    { category: 'city', word: 'تهران', level: 2 },
    { category: 'city', word: 'اصفهان', level: 3 },
    { category: 'city', word: 'شیراز', level: 2 },
    { category: 'city', word: 'مشهد', level: 3 },
    { category: 'city', word: 'تبریز', level: 2 },
    { category: 'city', word: 'اهواز', level: 3 },
    { category: 'city', word: 'قم', level: 1 },
    { category: 'city', word: 'کرج', level: 2 },
    { category: 'city', word: 'رشت', level: 2 },
    { category: 'city', word: 'ساری', level: 2 },
    { category: 'city', word: 'اردبیل', level: 3 },
    { category: 'city', word: 'ارومیه', level: 3 },
    { category: 'city', word: 'زنجان', level: 2 },
    { category: 'city', word: 'همدان', level: 2 },
    { category: 'city', word: 'کرمانشاه', level: 3 },
    { category: 'city', word: 'یاسوج', level: 4 },
    { category: 'city', word: 'شهرکرد', level: 3 },
    { category: 'city', word: 'یاسوج', level: 4 },
    { category: 'city', word: 'بوشهر', level: 2 },
    { category: 'city', word: 'بندرعباس', level: 3 },
    { category: 'city', word: 'زاهدان', level: 4 },
    { category: 'city', word: 'بیرجند', level: 3 },
    { category: 'city', word: 'سمنان', level: 2 },
    { category: 'city', word: 'گرگان', level: 2 },
    { category: 'city', word: 'بجنورد', level: 3 },
    { category: 'city', word: 'ایلام', level: 3 },
    { category: 'city', word: 'سنندج', level: 3 },
    { category: 'city', word: 'خرم آباد', level: 3 },
    { category: 'city', word: 'نیویورک', level: 3 },
    { category: 'city', word: 'پاریس', level: 2 },
    { category: 'city', word: 'لندن', level: 2 },
    { category: 'city', word: 'توکیو', level: 3 },
    { category: 'city', word: 'برلین', level: 2 },
    { category: 'city', word: 'رم', level: 2 },
    { category: 'city', word: 'مادرید', level: 3 },
    { category: 'city', word: 'مسکو', level: 3 },
    { category: 'city', word: 'پکن', level: 3 },
    { category: 'city', word: 'سیدنی', level: 3 },
    { category: 'city', word: 'تورنتو', level: 3 },
    { category: 'city', word: 'لس آنجلس', level: 4 },
    { category: 'city', word: 'شیکاگو', level: 3 },
    { category: 'city', word: 'میامی', level: 2 },
    { category: 'city', word: 'دبی', level: 2 },
    { category: 'city', word: 'استانبول', level: 3 },
    { category: 'city', word: 'قاهره', level: 3 },
    { category: 'city', word: 'ریودوژانیرو', level: 5 },
    { category: 'city', word: 'کیپ تاون', level: 4 },
    { category: 'city', word: 'بانکوک', level: 3 },

    // Countries
    { category: 'country', word: 'ایران', level: 1 },
    { category: 'country', word: 'افغانستان', level: 3 },
    { category: 'country', word: 'عراق', level: 2 },
    { category: 'country', word: 'ترکیه', level: 2 },
    { category: 'country', word: 'فرانسه', level: 2 },
    { category: 'country', word: 'آلمان', level: 2 },
    { category: 'country', word: 'ایتالیا', level: 3 },
    { category: 'country', word: 'اسپانیا', level: 3 },
    { category: 'country', word: 'روسیه', level: 2 },
    { category: 'country', word: 'چین', level: 1 },
    { category: 'country', word: 'ژاپن', level: 2 },
    { category: 'country', word: 'استرالیا', level: 3 },
    { category: 'country', word: 'کانادا', level: 2 },
    { category: 'country', word: 'ایالات متحده', level: 4 },
    { category: 'country', word: 'برزیل', level: 2 },
    { category: 'country', word: 'آرژانتین', level: 3 },
    { category: 'country', word: 'مکزیک', level: 2 },
    { category: 'country', word: 'هند', level: 1 },
    { category: 'country', word: 'پاکستان', level: 3 },
    { category: 'country', word: 'عربستان سعودی', level: 4 },
    { category: 'country', word: 'مصر', level: 2 },
    { category: 'country', word: 'انگلستان', level: 3 },
    { category: 'country', word: 'سوریه', level: 2 },
    { category: 'country', word: 'لبنان', level: 3 },
    { category: 'country', word: 'اسرائیل', level: 3 },
    { category: 'country', word: 'کره جنوبی', level: 3 },
    { category: 'country', word: 'کره شمالی', level: 3 },
    { category: 'country', word: 'ویتنام', level: 3 },
    { category: 'country', word: 'تایلند', level: 2 },
    { category: 'country', word: 'اندونزی', level: 3 },
    { category: 'country', word: 'مالزی', level: 2 },
    { category: 'country', word: 'سنگاپور', level: 3 },
    { category: 'country', word: 'نیوزیلند', level: 4 },
    { category: 'country', word: 'آفریقای جنوبی', level: 4 },
    { category: 'country', word: 'نیجریه', level: 3 },
    { category: 'country', word: 'کنیا', level: 2 },
    { category: 'country', word: 'مراکش', level: 3 },
    { category: 'country', word: 'تونس', level: 2 },
    { category: 'country', word: 'الجزایر', level: 3 },
    { category: 'country', word: 'سودان', level: 2 },
    { category: 'country', word: 'اتیوپی', level: 3 },
    { category: 'country', word: 'غنا', level: 2 },
    { category: 'country', word: 'ساحل عاج', level: 4 },
    { category: 'country', word: 'کامرون', level: 3 },
    { category: 'country', word: 'زامبیا', level: 3 },
    { category: 'country', word: 'زیمبابوه', level: 4 },

    // Fruits
    { category: 'fruit', word: 'سیب', level: 1 },
    { category: 'fruit', word: 'موز', level: 1 },
    { category: 'fruit', word: 'پرتقال', level: 2 },
    { category: 'fruit', word: 'انگور', level: 1 },
    { category: 'fruit', word: 'هندوانه', level: 3 },
    { category: 'fruit', word: 'خربزه', level: 2 },
    { category: 'fruit', word: 'آناناس', level: 3 },
    { category: 'fruit', word: 'کیوی', level: 2 },
    { category: 'fruit', word: 'توت فرنگی', level: 3 },
    { category: 'fruit', word: 'تمشک', level: 2 },
    { category: 'fruit', word: 'بلوبری', level: 3 },
    { category: 'fruit', word: 'لیمو', level: 1 },
    { category: 'fruit', word: 'گریپ فروت', level: 4 },
    { category: 'fruit', word: 'انار', level: 2 },
    { category: 'fruit', word: 'زردآلو', level: 2 },
    { category: 'fruit', word: 'هلو', level: 1 },
    { category: 'fruit', word: 'شلیل', level: 2 },
    { category: 'fruit', word: 'آلبالو', level: 2 },
    { category: 'fruit', word: 'گیلاس', level: 2 },
    { category: 'fruit', word: 'خرما', level: 2 },
    { category: 'fruit', word: 'نارگیل', level: 3 },
    { category: 'fruit', word: 'آووکادو', level: 3 },
    { category: 'fruit', word: 'پاپایا', level: 4 },
    { category: 'fruit', word: 'مانگو', level: 2 },
    { category: 'fruit', word: 'انجیر', level: 2 },
    { category: 'fruit', word: 'به', level: 1 },
    { category: 'fruit', word: 'گلابی', level: 2 },
    { category: 'fruit', word: 'طالبی', level: 2 },
    { category: 'fruit', word: 'شاه توت', level: 3 },
    { category: 'fruit', word: 'زغال اخته', level: 3 },
    { category: 'fruit', word: 'نارنگی', level: 2 },
    { category: 'fruit', word: 'لایم', level: 2 },
    { category: 'fruit', word: 'پوملو', level: 4 },
    { category: 'fruit', word: 'دراگون فروت', level: 4 },
    { category: 'fruit', word: 'پشن فروت', level: 4 },
    { category: 'fruit', word: 'گواوا', level: 3 },

    // Objects
    { category: 'object', word: 'کامپیوتر', level: 2 },
    { category: 'object', word: 'تلفن', level: 1 },
    { category: 'object', word: 'کتاب', level: 1 },
    { category: 'object', word: 'میز', level: 1 },
    { category: 'object', word: 'صندلی', level: 2 },
    { category: 'object', word: 'لامپ', level: 1 },
    { category: 'object', word: 'تلویزیون', level: 3 },
    { category: 'object', word: 'یخچال', level: 2 },
    { category: 'object', word: 'ماشین لباسشویی', level: 4 },
    { category: 'object', word: 'اجاق گاز', level: 3 },
    { category: 'object', word: 'مایکروویو', level: 3 },
    { category: 'object', word: 'جاروبرقی', level: 3 },
    { category: 'object', word: 'پنکه', level: 2 },
    { category: 'object', word: 'کولر', level: 2 },
    { category: 'object', word: 'بخاری', level: 2 },
    { category: 'object', word: 'ساعت', level: 1 },
    { category: 'object', word: 'آینه', level: 2 },
    { category: 'object', word: 'تختخواب', level: 3 },
    { category: 'object', word: 'کمد', level: 2 },
    { category: 'object', word: 'قالی', level: 2 },
    { category: 'object', word: 'پرده', level: 2 },
    { category: 'object', word: 'گلدان', level: 2 },
    { category: 'object', word: 'چاقو', level: 1 },
    { category: 'object', word: 'چنگال', level: 2 },
    { category: 'object', word: 'قاشق', level: 1 },
    { category: 'object', word: 'لیوان', level: 1 },
    { category: 'object', word: 'بشقاب', level: 2 },
    { category: 'object', word: 'کاسه', level: 1 },
    { category: 'object', word: 'دوچرخه', level: 2 },
    { category: 'object', word: 'ماشین', level: 2 },
    { category: 'object', word: 'موتورسیکلت', level: 4 },
    { category: 'object', word: 'هواپیما', level: 3 },
    { category: 'object', word: 'کشتی', level: 2 },
    { category: 'object', word: 'قطار', level: 2 },
    { category: 'object', word: 'اتوبوس', level: 3 },
    { category: 'object', word: 'تاکسی', level: 2 },
    { category: 'object', word: 'دوربین', level: 2 },
    { category: 'object', word: 'عینک', level: 2 },
    { category: 'object', word: 'کیف', level: 1 },
    { category: 'object', word: 'کفش', level: 1 },
    { category: 'object', word: 'لباس', level: 2 },
    { category: 'object', word: 'شلوار', level: 2 },
    { category: 'object', word: 'پیراهن', level: 3 },
    { category: 'object', word: 'کلاه', level: 1 },
    { category: 'object', word: 'دستکش', level: 2 },

    // Names
    { category: 'name', word: 'علی', level: 1 },
    { category: 'name', word: 'محمد', level: 1 },
    { category: 'name', word: 'فاطمه', level: 2 },
    { category: 'name', word: 'زهرا', level: 1 },
    { category: 'name', word: 'حسین', level: 2 },
    { category: 'name', word: 'رضا', level: 1 },
    { category: 'name', word: 'مریم', level: 2 },
    { category: 'name', word: 'سارا', level: 1 },
    { category: 'name', word: 'احمد', level: 2 },
    { category: 'name', word: 'مهدی', level: 2 },
    { category: 'name', word: 'امیر', level: 1 },
    { category: 'name', word: 'نازنین', level: 3 },
    { category: 'name', word: 'پریسا', level: 3 },
    { category: 'name', word: 'بهار', level: 2 },
    { category: 'name', word: 'سامان', level: 2 },
    { category: 'name', word: 'کیان', level: 2 },
    { category: 'name', word: 'آرش', level: 2 },
    { category: 'name', word: 'سهراب', level: 3 },
    { category: 'name', word: 'رستم', level: 2 },
    { category: 'name', word: 'مینا', level: 2 },
    { category: 'name', word: 'لیلا', level: 2 },
    { category: 'name', word: 'شیرین', level: 3 },
    { category: 'name', word: 'فرهاد', level: 3 },
    { category: 'name', word: 'کامران', level: 3 },
    { category: 'name', word: 'نیلوفر', level: 3 },
    { category: 'name', word: 'رویا', level: 2 },
    { category: 'name', word: 'باران', level: 2 },
    { category: 'name', word: 'آرین', level: 2 },
    { category: 'name', word: 'دلارام', level: 3 },
    { category: 'name', word: 'فرزاد', level: 3 },
    { category: 'name', word: 'گلناز', level: 3 },
    { category: 'name', word: 'هادی', level: 2 },
    { category: 'name', word: 'یاسمن', level: 3 },
    { category: 'name', word: 'پدرام', level: 3 },
    { category: 'name', word: 'ترانه', level: 3 },
    { category: 'name', word: 'سپهر', level: 2 },
    { category: 'name', word: 'نسترن', level: 3 },
    { category: 'name', word: 'بهروز', level: 3 },
    { category: 'name', word: 'شادی', level: 2 },
    { category: 'name', word: 'کوروش', level: 3 },
    { category: 'name', word: 'داریوش', level: 3 },
    { category: 'name', word: 'پروانه', level: 3 },
    { category: 'name', word: 'مهران', level: 3 },
    { category: 'name', word: 'آتوسا', level: 3 },
    { category: 'name', word: 'اردوان', level: 4 },
    { category: 'name', word: 'سیما', level: 2 },
    { category: 'name', word: 'بهنام', level: 3 },
    { category: 'name', word: 'نیکا', level: 2 },
    { category: 'name', word: 'آریا', level: 2 },
    { category: 'name', word: 'مهسا', level: 2 },
    { category: 'name', word: 'پوریا', level: 3 },
    { category: 'name', word: 'ساناز', level: 3 }
];
